// Auto-generated by scripts/lv_conf_gen.py - do not edit by hand.

import { GetBridge } from "./bridge";

const lv_conf = GetBridge().NativeRender.lv_conf;

/** Read once at module load; hot paths use these plain numbers. */

// coord constants begin - deps/lvgl/src/misc/lv_area.h
export const LV_COORD_MAX = lv_conf.LV_COORD_MAX;
// coord constants end - deps/lvgl/src/misc/lv_area.h

// lv_part_t begin - deps/lvgl/src/core/lv_obj.h
/** A background like rectangle */
export const LV_PART_MAIN = lv_conf.LV_PART_MAIN;
/** The scrollbar(s) */
export const LV_PART_SCROLLBAR = lv_conf.LV_PART_SCROLLBAR;
/** Indicator, e.g. for slider, bar, switch, or the tick box of the checkbox */
export const LV_PART_INDICATOR = lv_conf.LV_PART_INDICATOR;
/** Like handle to grab to adjust the value */
export const LV_PART_KNOB = lv_conf.LV_PART_KNOB;
/** Indicate the currently selected option or section */
export const LV_PART_SELECTED = lv_conf.LV_PART_SELECTED;
/** Used if the widget has multiple similar elements (e.g. table cells) */
export const LV_PART_ITEMS = lv_conf.LV_PART_ITEMS;
/** Ticks on scale e.g. for a chart or meter */
export const LV_PART_TICKS = lv_conf.LV_PART_TICKS;
/** Mark a specific place e.g. for text area's cursor or on a chart */
export const LV_PART_CURSOR = lv_conf.LV_PART_CURSOR;

/** Extension point for custom widgets */
export const LV_PART_CUSTOM_FIRST = lv_conf.LV_PART_CUSTOM_FIRST;

/** Special value can be used in some functions to target all parts */
export const LV_PART_ANY = lv_conf.LV_PART_ANY;
// lv_part_t end - deps/lvgl/src/core/lv_obj.h

// lv_state_t begin - deps/lvgl/src/core/lv_obj.h
export const LV_STATE_DEFAULT = lv_conf.LV_STATE_DEFAULT;
export const LV_STATE_CHECKED = lv_conf.LV_STATE_CHECKED;
export const LV_STATE_FOCUSED = lv_conf.LV_STATE_FOCUSED;
export const LV_STATE_FOCUS_KEY = lv_conf.LV_STATE_FOCUS_KEY;
export const LV_STATE_EDITED = lv_conf.LV_STATE_EDITED;
export const LV_STATE_HOVERED = lv_conf.LV_STATE_HOVERED;
export const LV_STATE_PRESSED = lv_conf.LV_STATE_PRESSED;
export const LV_STATE_SCROLLED = lv_conf.LV_STATE_SCROLLED;
export const LV_STATE_DISABLED = lv_conf.LV_STATE_DISABLED;

export const LV_STATE_USER_1 = lv_conf.LV_STATE_USER_1;
export const LV_STATE_USER_2 = lv_conf.LV_STATE_USER_2;
export const LV_STATE_USER_3 = lv_conf.LV_STATE_USER_3;
export const LV_STATE_USER_4 = lv_conf.LV_STATE_USER_4;

/** Special value can be used in some functions to target all states */
export const LV_STATE_ANY = lv_conf.LV_STATE_ANY;
// lv_state_t end - deps/lvgl/src/core/lv_obj.h

// lv_align_t begin - deps/lvgl/src/misc/lv_area.h
export const LV_ALIGN_DEFAULT = lv_conf.LV_ALIGN_DEFAULT;
export const LV_ALIGN_TOP_LEFT = lv_conf.LV_ALIGN_TOP_LEFT;
export const LV_ALIGN_TOP_MID = lv_conf.LV_ALIGN_TOP_MID;
export const LV_ALIGN_TOP_RIGHT = lv_conf.LV_ALIGN_TOP_RIGHT;
export const LV_ALIGN_BOTTOM_LEFT = lv_conf.LV_ALIGN_BOTTOM_LEFT;
export const LV_ALIGN_BOTTOM_MID = lv_conf.LV_ALIGN_BOTTOM_MID;
export const LV_ALIGN_BOTTOM_RIGHT = lv_conf.LV_ALIGN_BOTTOM_RIGHT;
export const LV_ALIGN_LEFT_MID = lv_conf.LV_ALIGN_LEFT_MID;
export const LV_ALIGN_RIGHT_MID = lv_conf.LV_ALIGN_RIGHT_MID;
export const LV_ALIGN_CENTER = lv_conf.LV_ALIGN_CENTER;

export const LV_ALIGN_OUT_TOP_LEFT = lv_conf.LV_ALIGN_OUT_TOP_LEFT;
export const LV_ALIGN_OUT_TOP_MID = lv_conf.LV_ALIGN_OUT_TOP_MID;
export const LV_ALIGN_OUT_TOP_RIGHT = lv_conf.LV_ALIGN_OUT_TOP_RIGHT;
export const LV_ALIGN_OUT_BOTTOM_LEFT = lv_conf.LV_ALIGN_OUT_BOTTOM_LEFT;
export const LV_ALIGN_OUT_BOTTOM_MID = lv_conf.LV_ALIGN_OUT_BOTTOM_MID;
export const LV_ALIGN_OUT_BOTTOM_RIGHT = lv_conf.LV_ALIGN_OUT_BOTTOM_RIGHT;
export const LV_ALIGN_OUT_LEFT_TOP = lv_conf.LV_ALIGN_OUT_LEFT_TOP;
export const LV_ALIGN_OUT_LEFT_MID = lv_conf.LV_ALIGN_OUT_LEFT_MID;
export const LV_ALIGN_OUT_LEFT_BOTTOM = lv_conf.LV_ALIGN_OUT_LEFT_BOTTOM;
export const LV_ALIGN_OUT_RIGHT_TOP = lv_conf.LV_ALIGN_OUT_RIGHT_TOP;
export const LV_ALIGN_OUT_RIGHT_MID = lv_conf.LV_ALIGN_OUT_RIGHT_MID;
export const LV_ALIGN_OUT_RIGHT_BOTTOM = lv_conf.LV_ALIGN_OUT_RIGHT_BOTTOM;
// lv_align_t end - deps/lvgl/src/misc/lv_area.h

// lv_dir_t begin - deps/lvgl/src/misc/lv_area.h
export const LV_DIR_NONE = lv_conf.LV_DIR_NONE;
export const LV_DIR_LEFT = lv_conf.LV_DIR_LEFT;
export const LV_DIR_RIGHT = lv_conf.LV_DIR_RIGHT;
export const LV_DIR_TOP = lv_conf.LV_DIR_TOP;
export const LV_DIR_BOTTOM = lv_conf.LV_DIR_BOTTOM;
export const LV_DIR_HOR = lv_conf.LV_DIR_HOR;
export const LV_DIR_VER = lv_conf.LV_DIR_VER;
export const LV_DIR_ALL = lv_conf.LV_DIR_ALL;
// lv_dir_t end - deps/lvgl/src/misc/lv_area.h

// lv_flex_flow_t begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h
export const LV_FLEX_FLOW_ROW = lv_conf.LV_FLEX_FLOW_ROW;
export const LV_FLEX_FLOW_COLUMN = lv_conf.LV_FLEX_FLOW_COLUMN;
export const LV_FLEX_FLOW_ROW_WRAP = lv_conf.LV_FLEX_FLOW_ROW_WRAP;
export const LV_FLEX_FLOW_ROW_REVERSE = lv_conf.LV_FLEX_FLOW_ROW_REVERSE;
export const LV_FLEX_FLOW_ROW_WRAP_REVERSE = lv_conf.LV_FLEX_FLOW_ROW_WRAP_REVERSE;
export const LV_FLEX_FLOW_COLUMN_WRAP = lv_conf.LV_FLEX_FLOW_COLUMN_WRAP;
export const LV_FLEX_FLOW_COLUMN_REVERSE = lv_conf.LV_FLEX_FLOW_COLUMN_REVERSE;
export const LV_FLEX_FLOW_COLUMN_WRAP_REVERSE = lv_conf.LV_FLEX_FLOW_COLUMN_WRAP_REVERSE;
// lv_flex_flow_t end - deps/lvgl/src/extra/layouts/flex/lv_flex.h

// lv_flex_align_t begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h
export const LV_FLEX_ALIGN_START = lv_conf.LV_FLEX_ALIGN_START;
export const LV_FLEX_ALIGN_END = lv_conf.LV_FLEX_ALIGN_END;
export const LV_FLEX_ALIGN_CENTER = lv_conf.LV_FLEX_ALIGN_CENTER;
export const LV_FLEX_ALIGN_SPACE_EVENLY = lv_conf.LV_FLEX_ALIGN_SPACE_EVENLY;
export const LV_FLEX_ALIGN_SPACE_AROUND = lv_conf.LV_FLEX_ALIGN_SPACE_AROUND;
export const LV_FLEX_ALIGN_SPACE_BETWEEN = lv_conf.LV_FLEX_ALIGN_SPACE_BETWEEN;
// lv_flex_align_t end - deps/lvgl/src/extra/layouts/flex/lv_flex.h

// lv_layout_flex begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h
export const LV_LAYOUT_FLEX = lv_conf.LV_LAYOUT_FLEX;
// lv_layout_flex end - deps/lvgl/src/extra/layouts/flex/lv_flex.h

// lv_layout_grid begin - deps/lvgl/src/extra/layouts/grid/lv_grid.h
export const LV_LAYOUT_GRID = lv_conf.LV_LAYOUT_GRID;
// lv_layout_grid end - deps/lvgl/src/extra/layouts/grid/lv_grid.h

// lv_grid_align_t begin - deps/lvgl/src/extra/layouts/grid/lv_grid.h
export const LV_GRID_ALIGN_START = lv_conf.LV_GRID_ALIGN_START;
export const LV_GRID_ALIGN_CENTER = lv_conf.LV_GRID_ALIGN_CENTER;
export const LV_GRID_ALIGN_END = lv_conf.LV_GRID_ALIGN_END;
export const LV_GRID_ALIGN_STRETCH = lv_conf.LV_GRID_ALIGN_STRETCH;
export const LV_GRID_ALIGN_SPACE_EVENLY = lv_conf.LV_GRID_ALIGN_SPACE_EVENLY;
export const LV_GRID_ALIGN_SPACE_AROUND = lv_conf.LV_GRID_ALIGN_SPACE_AROUND;
export const LV_GRID_ALIGN_SPACE_BETWEEN = lv_conf.LV_GRID_ALIGN_SPACE_BETWEEN;
// lv_grid_align_t end - deps/lvgl/src/extra/layouts/grid/lv_grid.h

// lv_scroll_snap_t begin - deps/lvgl/src/core/lv_obj_scroll.h
/** Do not align, leave where it is */
export const LV_SCROLL_SNAP_NONE = lv_conf.LV_SCROLL_SNAP_NONE;
/** Align to the left/top */
export const LV_SCROLL_SNAP_START = lv_conf.LV_SCROLL_SNAP_START;
/** Align to the right/bottom */
export const LV_SCROLL_SNAP_END = lv_conf.LV_SCROLL_SNAP_END;
/** Align to the center */
export const LV_SCROLL_SNAP_CENTER = lv_conf.LV_SCROLL_SNAP_CENTER;
// lv_scroll_snap_t end - deps/lvgl/src/core/lv_obj_scroll.h

// lv_text_align_t begin - deps/lvgl/src/misc/lv_txt.h
/** Align text auto */
export const LV_TEXT_ALIGN_AUTO = lv_conf.LV_TEXT_ALIGN_AUTO;
/** Align text to left */
export const LV_TEXT_ALIGN_LEFT = lv_conf.LV_TEXT_ALIGN_LEFT;
/** Align text to center */
export const LV_TEXT_ALIGN_CENTER = lv_conf.LV_TEXT_ALIGN_CENTER;
/** Align text to right */
export const LV_TEXT_ALIGN_RIGHT = lv_conf.LV_TEXT_ALIGN_RIGHT;
// lv_text_align_t end - deps/lvgl/src/misc/lv_txt.h

// lv_text_decor_t begin - deps/lvgl/src/misc/lv_style.h
export const LV_TEXT_DECOR_NONE = lv_conf.LV_TEXT_DECOR_NONE;
export const LV_TEXT_DECOR_UNDERLINE = lv_conf.LV_TEXT_DECOR_UNDERLINE;
export const LV_TEXT_DECOR_STRIKETHROUGH = lv_conf.LV_TEXT_DECOR_STRIKETHROUGH;
// lv_text_decor_t end - deps/lvgl/src/misc/lv_style.h

// lv_grad_dir_t begin - deps/lvgl/src/misc/lv_style.h
/** No gradient (the `grad_color` property is ignored) */
export const LV_GRAD_DIR_NONE = lv_conf.LV_GRAD_DIR_NONE;
/** Vertical (top to bottom) gradient */
export const LV_GRAD_DIR_VER = lv_conf.LV_GRAD_DIR_VER;
/** Horizontal (left to right) gradient */
export const LV_GRAD_DIR_HOR = lv_conf.LV_GRAD_DIR_HOR;
// lv_grad_dir_t end - deps/lvgl/src/misc/lv_style.h

// lv_border_side_t begin - deps/lvgl/src/misc/lv_style.h
export const LV_BORDER_SIDE_NONE = lv_conf.LV_BORDER_SIDE_NONE;
export const LV_BORDER_SIDE_BOTTOM = lv_conf.LV_BORDER_SIDE_BOTTOM;
export const LV_BORDER_SIDE_TOP = lv_conf.LV_BORDER_SIDE_TOP;
export const LV_BORDER_SIDE_LEFT = lv_conf.LV_BORDER_SIDE_LEFT;
export const LV_BORDER_SIDE_RIGHT = lv_conf.LV_BORDER_SIDE_RIGHT;
export const LV_BORDER_SIDE_FULL = lv_conf.LV_BORDER_SIDE_FULL;
/** FOR matrix-like objects (e.g. Button matrix) */
export const LV_BORDER_SIDE_INTERNAL = lv_conf.LV_BORDER_SIDE_INTERNAL;
// lv_border_side_t end - deps/lvgl/src/misc/lv_style.h

// lv_label_long_mode_t begin - deps/lvgl/src/widgets/lv_label.h
/** Keep the object width, wrap the too long lines and expand the object height */
export const LV_LABEL_LONG_WRAP = lv_conf.LV_LABEL_LONG_WRAP;
/** Keep the size and write dots at the end if the text is too long */
export const LV_LABEL_LONG_DOT = lv_conf.LV_LABEL_LONG_DOT;
/** Keep the size and roll the text back and forth */
export const LV_LABEL_LONG_SCROLL = lv_conf.LV_LABEL_LONG_SCROLL;
/** Keep the size and roll the text circularly */
export const LV_LABEL_LONG_SCROLL_CIRCULAR = lv_conf.LV_LABEL_LONG_SCROLL_CIRCULAR;
/** Keep the size and clip the text out of it */
export const LV_LABEL_LONG_CLIP = lv_conf.LV_LABEL_LONG_CLIP;
// lv_label_long_mode_t end - deps/lvgl/src/widgets/lv_label.h

// lv_style_prop_meta begin - deps/lvgl/src/misc/lv_style.h
export const LV_STYLE_PROP_FLAG_NONE = lv_conf.LV_STYLE_PROP_FLAG_NONE;
export const LV_STYLE_PROP_INHERIT = lv_conf.LV_STYLE_PROP_INHERIT;
export const LV_STYLE_PROP_EXT_DRAW = lv_conf.LV_STYLE_PROP_EXT_DRAW;
export const LV_STYLE_PROP_LAYOUT_REFR = lv_conf.LV_STYLE_PROP_LAYOUT_REFR;
export const LV_STYLE_PROP_PARENT_LAYOUT_REFR = lv_conf.LV_STYLE_PROP_PARENT_LAYOUT_REFR;
export const LV_STYLE_PROP_LAYER_REFR = lv_conf.LV_STYLE_PROP_LAYER_REFR;
export const LV_STYLE_PROP_ALL = lv_conf.LV_STYLE_PROP_ALL;
export const LV_STYLE_PROP_META_INHERIT = lv_conf.LV_STYLE_PROP_META_INHERIT;
export const LV_STYLE_PROP_META_INITIAL = lv_conf.LV_STYLE_PROP_META_INITIAL;
export const LV_STYLE_PROP_META_MASK = lv_conf.LV_STYLE_PROP_META_MASK;
// lv_style_prop_meta end - deps/lvgl/src/misc/lv_style.h

// lv_style_prop_t begin - deps/lvgl/src/misc/lv_style.h
export const LV_STYLE_PROP_INV = lv_conf.LV_STYLE_PROP_INV;

/** Group 0 */
export const LV_STYLE_WIDTH = lv_conf.LV_STYLE_WIDTH;
export const LV_STYLE_MIN_WIDTH = lv_conf.LV_STYLE_MIN_WIDTH;
export const LV_STYLE_MAX_WIDTH = lv_conf.LV_STYLE_MAX_WIDTH;
export const LV_STYLE_HEIGHT = lv_conf.LV_STYLE_HEIGHT;
export const LV_STYLE_MIN_HEIGHT = lv_conf.LV_STYLE_MIN_HEIGHT;
export const LV_STYLE_MAX_HEIGHT = lv_conf.LV_STYLE_MAX_HEIGHT;
export const LV_STYLE_X = lv_conf.LV_STYLE_X;
export const LV_STYLE_Y = lv_conf.LV_STYLE_Y;
export const LV_STYLE_ALIGN = lv_conf.LV_STYLE_ALIGN;
export const LV_STYLE_LAYOUT = lv_conf.LV_STYLE_LAYOUT;
export const LV_STYLE_RADIUS = lv_conf.LV_STYLE_RADIUS;

/** Group 1 */
export const LV_STYLE_PAD_TOP = lv_conf.LV_STYLE_PAD_TOP;
export const LV_STYLE_PAD_BOTTOM = lv_conf.LV_STYLE_PAD_BOTTOM;
export const LV_STYLE_PAD_LEFT = lv_conf.LV_STYLE_PAD_LEFT;
export const LV_STYLE_PAD_RIGHT = lv_conf.LV_STYLE_PAD_RIGHT;
export const LV_STYLE_PAD_ROW = lv_conf.LV_STYLE_PAD_ROW;
export const LV_STYLE_PAD_COLUMN = lv_conf.LV_STYLE_PAD_COLUMN;
export const LV_STYLE_BASE_DIR = lv_conf.LV_STYLE_BASE_DIR;
export const LV_STYLE_CLIP_CORNER = lv_conf.LV_STYLE_CLIP_CORNER;

/** Group 2 */
export const LV_STYLE_BG_COLOR = lv_conf.LV_STYLE_BG_COLOR;
export const LV_STYLE_BG_OPA = lv_conf.LV_STYLE_BG_OPA;
export const LV_STYLE_BG_GRAD_COLOR = lv_conf.LV_STYLE_BG_GRAD_COLOR;
export const LV_STYLE_BG_GRAD_DIR = lv_conf.LV_STYLE_BG_GRAD_DIR;
export const LV_STYLE_BG_MAIN_STOP = lv_conf.LV_STYLE_BG_MAIN_STOP;
export const LV_STYLE_BG_GRAD_STOP = lv_conf.LV_STYLE_BG_GRAD_STOP;
export const LV_STYLE_BG_GRAD = lv_conf.LV_STYLE_BG_GRAD;
export const LV_STYLE_BG_DITHER_MODE = lv_conf.LV_STYLE_BG_DITHER_MODE;
export const LV_STYLE_BG_IMG_SRC = lv_conf.LV_STYLE_BG_IMG_SRC;
export const LV_STYLE_BG_IMG_OPA = lv_conf.LV_STYLE_BG_IMG_OPA;
export const LV_STYLE_BG_IMG_RECOLOR = lv_conf.LV_STYLE_BG_IMG_RECOLOR;
export const LV_STYLE_BG_IMG_RECOLOR_OPA = lv_conf.LV_STYLE_BG_IMG_RECOLOR_OPA;
export const LV_STYLE_BG_IMG_TILED = lv_conf.LV_STYLE_BG_IMG_TILED;

/** Group 3 */
export const LV_STYLE_BORDER_COLOR = lv_conf.LV_STYLE_BORDER_COLOR;
export const LV_STYLE_BORDER_OPA = lv_conf.LV_STYLE_BORDER_OPA;
export const LV_STYLE_BORDER_WIDTH = lv_conf.LV_STYLE_BORDER_WIDTH;
export const LV_STYLE_BORDER_SIDE = lv_conf.LV_STYLE_BORDER_SIDE;
export const LV_STYLE_BORDER_POST = lv_conf.LV_STYLE_BORDER_POST;
export const LV_STYLE_OUTLINE_WIDTH = lv_conf.LV_STYLE_OUTLINE_WIDTH;
export const LV_STYLE_OUTLINE_COLOR = lv_conf.LV_STYLE_OUTLINE_COLOR;
export const LV_STYLE_OUTLINE_OPA = lv_conf.LV_STYLE_OUTLINE_OPA;
export const LV_STYLE_OUTLINE_PAD = lv_conf.LV_STYLE_OUTLINE_PAD;

/** Group 4 */
export const LV_STYLE_SHADOW_WIDTH = lv_conf.LV_STYLE_SHADOW_WIDTH;
export const LV_STYLE_SHADOW_OFS_X = lv_conf.LV_STYLE_SHADOW_OFS_X;
export const LV_STYLE_SHADOW_OFS_Y = lv_conf.LV_STYLE_SHADOW_OFS_Y;
export const LV_STYLE_SHADOW_SPREAD = lv_conf.LV_STYLE_SHADOW_SPREAD;
export const LV_STYLE_SHADOW_COLOR = lv_conf.LV_STYLE_SHADOW_COLOR;
export const LV_STYLE_SHADOW_OPA = lv_conf.LV_STYLE_SHADOW_OPA;
export const LV_STYLE_IMG_OPA = lv_conf.LV_STYLE_IMG_OPA;
export const LV_STYLE_IMG_RECOLOR = lv_conf.LV_STYLE_IMG_RECOLOR;
export const LV_STYLE_IMG_RECOLOR_OPA = lv_conf.LV_STYLE_IMG_RECOLOR_OPA;
export const LV_STYLE_LINE_WIDTH = lv_conf.LV_STYLE_LINE_WIDTH;
export const LV_STYLE_LINE_DASH_WIDTH = lv_conf.LV_STYLE_LINE_DASH_WIDTH;
export const LV_STYLE_LINE_DASH_GAP = lv_conf.LV_STYLE_LINE_DASH_GAP;
export const LV_STYLE_LINE_ROUNDED = lv_conf.LV_STYLE_LINE_ROUNDED;
export const LV_STYLE_LINE_COLOR = lv_conf.LV_STYLE_LINE_COLOR;
export const LV_STYLE_LINE_OPA = lv_conf.LV_STYLE_LINE_OPA;

/** Group 5 */
export const LV_STYLE_ARC_WIDTH = lv_conf.LV_STYLE_ARC_WIDTH;
export const LV_STYLE_ARC_ROUNDED = lv_conf.LV_STYLE_ARC_ROUNDED;
export const LV_STYLE_ARC_COLOR = lv_conf.LV_STYLE_ARC_COLOR;
export const LV_STYLE_ARC_OPA = lv_conf.LV_STYLE_ARC_OPA;
export const LV_STYLE_ARC_IMG_SRC = lv_conf.LV_STYLE_ARC_IMG_SRC;
export const LV_STYLE_TEXT_COLOR = lv_conf.LV_STYLE_TEXT_COLOR;
export const LV_STYLE_TEXT_OPA = lv_conf.LV_STYLE_TEXT_OPA;
export const LV_STYLE_TEXT_FONT = lv_conf.LV_STYLE_TEXT_FONT;
export const LV_STYLE_TEXT_LETTER_SPACE = lv_conf.LV_STYLE_TEXT_LETTER_SPACE;
export const LV_STYLE_TEXT_LINE_SPACE = lv_conf.LV_STYLE_TEXT_LINE_SPACE;
export const LV_STYLE_TEXT_DECOR = lv_conf.LV_STYLE_TEXT_DECOR;
export const LV_STYLE_TEXT_ALIGN = lv_conf.LV_STYLE_TEXT_ALIGN;

/** Group 6 */
export const LV_STYLE_OPA = lv_conf.LV_STYLE_OPA;
export const LV_STYLE_COLOR_FILTER_DSC = lv_conf.LV_STYLE_COLOR_FILTER_DSC;
export const LV_STYLE_COLOR_FILTER_OPA = lv_conf.LV_STYLE_COLOR_FILTER_OPA;
export const LV_STYLE_ANIM = lv_conf.LV_STYLE_ANIM;
export const LV_STYLE_ANIM_TIME = lv_conf.LV_STYLE_ANIM_TIME;
export const LV_STYLE_ANIM_SPEED = lv_conf.LV_STYLE_ANIM_SPEED;
export const LV_STYLE_TRANSITION = lv_conf.LV_STYLE_TRANSITION;
export const LV_STYLE_BLEND_MODE = lv_conf.LV_STYLE_BLEND_MODE;
export const LV_STYLE_TRANSFORM_WIDTH = lv_conf.LV_STYLE_TRANSFORM_WIDTH;
export const LV_STYLE_TRANSFORM_HEIGHT = lv_conf.LV_STYLE_TRANSFORM_HEIGHT;
export const LV_STYLE_TRANSLATE_X = lv_conf.LV_STYLE_TRANSLATE_X;
export const LV_STYLE_TRANSLATE_Y = lv_conf.LV_STYLE_TRANSLATE_Y;
export const LV_STYLE_TRANSFORM_ZOOM = lv_conf.LV_STYLE_TRANSFORM_ZOOM;
export const LV_STYLE_TRANSFORM_ANGLE = lv_conf.LV_STYLE_TRANSFORM_ANGLE;
export const LV_STYLE_TRANSFORM_PIVOT_X = lv_conf.LV_STYLE_TRANSFORM_PIVOT_X;
export const LV_STYLE_TRANSFORM_PIVOT_Y = lv_conf.LV_STYLE_TRANSFORM_PIVOT_Y;

export const LV_STYLE_LAST_BUILT_IN_PROP = lv_conf.LV_STYLE_LAST_BUILT_IN_PROP;
export const LV_STYLE_NUM_BUILT_IN_PROPS = lv_conf.LV_STYLE_NUM_BUILT_IN_PROPS;

export const LV_STYLE_PROP_ANY = lv_conf.LV_STYLE_PROP_ANY;
// lv_style_prop_t end - deps/lvgl/src/misc/lv_style.h

// lv_style_prop_t_extend_flow begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h
export const LV_STYLE_FLEX_FLOW = lv_conf.LV_STYLE_FLEX_FLOW;
export const LV_STYLE_FLEX_MAIN_PLACE = lv_conf.LV_STYLE_FLEX_MAIN_PLACE;
export const LV_STYLE_FLEX_CROSS_PLACE = lv_conf.LV_STYLE_FLEX_CROSS_PLACE;
export const LV_STYLE_FLEX_TRACK_PLACE = lv_conf.LV_STYLE_FLEX_TRACK_PLACE;
export const LV_STYLE_FLEX_GROW = lv_conf.LV_STYLE_FLEX_GROW;
// lv_style_prop_t_extend_flow end - deps/lvgl/src/extra/layouts/flex/lv_flex.h

// lv_style_prop_t_extend_grid begin - deps/lvgl/src/extra/layouts/grid/lv_grid.h
export const LV_STYLE_GRID_COLUMN_DSC_ARRAY = lv_conf.LV_STYLE_GRID_COLUMN_DSC_ARRAY;
export const LV_STYLE_GRID_COLUMN_ALIGN = lv_conf.LV_STYLE_GRID_COLUMN_ALIGN;
export const LV_STYLE_GRID_ROW_DSC_ARRAY = lv_conf.LV_STYLE_GRID_ROW_DSC_ARRAY;
export const LV_STYLE_GRID_ROW_ALIGN = lv_conf.LV_STYLE_GRID_ROW_ALIGN;
export const LV_STYLE_GRID_CELL_COLUMN_POS = lv_conf.LV_STYLE_GRID_CELL_COLUMN_POS;
export const LV_STYLE_GRID_CELL_COLUMN_SPAN = lv_conf.LV_STYLE_GRID_CELL_COLUMN_SPAN;
export const LV_STYLE_GRID_CELL_X_ALIGN = lv_conf.LV_STYLE_GRID_CELL_X_ALIGN;
export const LV_STYLE_GRID_CELL_ROW_POS = lv_conf.LV_STYLE_GRID_CELL_ROW_POS;
export const LV_STYLE_GRID_CELL_ROW_SPAN = lv_conf.LV_STYLE_GRID_CELL_ROW_SPAN;
export const LV_STYLE_GRID_CELL_Y_ALIGN = lv_conf.LV_STYLE_GRID_CELL_Y_ALIGN;
// lv_style_prop_t_extend_grid end - deps/lvgl/src/extra/layouts/grid/lv_grid.h

// lv_style_prop_t_extend_css begin - src/render/native/core/lv_conf/lv_style_prop_extend.h
export const LV_STYLE_CSS_CHART_SCALE_X = lv_conf.LV_STYLE_CSS_CHART_SCALE_X;
export const LV_STYLE_CSS_CHART_SCALE_Y = lv_conf.LV_STYLE_CSS_CHART_SCALE_Y;
export const LV_STYLE_CSS_DISPLAY = lv_conf.LV_STYLE_CSS_DISPLAY;
export const LV_STYLE_CSS_FLEX_ALIGN = lv_conf.LV_STYLE_CSS_FLEX_ALIGN;
export const LV_STYLE_CSS_GRID_ALIGN = lv_conf.LV_STYLE_CSS_GRID_ALIGN;
export const LV_STYLE_CSS_GRID_CHILD = lv_conf.LV_STYLE_CSS_GRID_CHILD;
export const LV_STYLE_CSS_GRID_TEMPLATE = lv_conf.LV_STYLE_CSS_GRID_TEMPLATE;
export const LV_STYLE_CSS_IMG_ORIGIN = lv_conf.LV_STYLE_CSS_IMG_ORIGIN;
export const LV_STYLE_CSS_IMG_ROTATE = lv_conf.LV_STYLE_CSS_IMG_ROTATE;
export const LV_STYLE_CSS_IMG_SCALE = lv_conf.LV_STYLE_CSS_IMG_SCALE;
export const LV_STYLE_CSS_OVERFLOW = lv_conf.LV_STYLE_CSS_OVERFLOW;
export const LV_STYLE_CSS_OVERFLOW_SCROLLING = lv_conf.LV_STYLE_CSS_OVERFLOW_SCROLLING;
export const LV_STYLE_CSS_POSITION = lv_conf.LV_STYLE_CSS_POSITION;
export const LV_STYLE_CSS_SCROLL_ENABLE_SNAP = lv_conf.LV_STYLE_CSS_SCROLL_ENABLE_SNAP;
export const LV_STYLE_CSS_SCROLL_SNAP_X = lv_conf.LV_STYLE_CSS_SCROLL_SNAP_X;
export const LV_STYLE_CSS_SCROLL_SNAP_Y = lv_conf.LV_STYLE_CSS_SCROLL_SNAP_Y;
export const LV_STYLE_CSS_TEXT_OVERFLOW = lv_conf.LV_STYLE_CSS_TEXT_OVERFLOW;
// lv_style_prop_t_extend_css end - src/render/native/core/lv_conf/lv_style_prop_extend.h

// lv_event_code_t begin - deps/lvgl/src/core/lv_event.h
export const LV_EVENT_ALL = lv_conf.LV_EVENT_ALL;

/** Input device events */
/** The object has been pressed */
export const LV_EVENT_PRESSED = lv_conf.LV_EVENT_PRESSED;
/** The object is being pressed (called continuously while pressing) */
export const LV_EVENT_PRESSING = lv_conf.LV_EVENT_PRESSING;
/** The object is still being pressed but slid cursor/finger off of the object */
export const LV_EVENT_PRESS_LOST = lv_conf.LV_EVENT_PRESS_LOST;
/** The object was pressed for a short period of time, then released it. Not called if scrolled. */
export const LV_EVENT_SHORT_CLICKED = lv_conf.LV_EVENT_SHORT_CLICKED;
/** Object has been pressed for at least `long_press_time`.  Not called if scrolled. */
export const LV_EVENT_LONG_PRESSED = lv_conf.LV_EVENT_LONG_PRESSED;
/** Called after `long_press_time` in every `long_press_repeat_time` ms.  Not called if scrolled. */
export const LV_EVENT_LONG_PRESSED_REPEAT = lv_conf.LV_EVENT_LONG_PRESSED_REPEAT;
/** Called on release if not scrolled (regardless to long press) */
export const LV_EVENT_CLICKED = lv_conf.LV_EVENT_CLICKED;
/** Called in every cases when the object has been released */
export const LV_EVENT_RELEASED = lv_conf.LV_EVENT_RELEASED;
/** Scrolling begins. The event parameter is a pointer to the animation of the scroll. Can be modified */
export const LV_EVENT_SCROLL_BEGIN = lv_conf.LV_EVENT_SCROLL_BEGIN;
/** Scrolling ends */
export const LV_EVENT_SCROLL_END = lv_conf.LV_EVENT_SCROLL_END;
/** Scrolling */
export const LV_EVENT_SCROLL = lv_conf.LV_EVENT_SCROLL;
/** A gesture is detected. Get the gesture with `lv_indev_get_gesture_dir(lv_indev_get_act());` */
export const LV_EVENT_GESTURE = lv_conf.LV_EVENT_GESTURE;
/** A key is sent to the object. Get the key with `lv_indev_get_key(lv_indev_get_act());` */
export const LV_EVENT_KEY = lv_conf.LV_EVENT_KEY;
/** The object is focused */
export const LV_EVENT_FOCUSED = lv_conf.LV_EVENT_FOCUSED;
/** The object is defocused */
export const LV_EVENT_DEFOCUSED = lv_conf.LV_EVENT_DEFOCUSED;
/** The object is defocused but still selected */
export const LV_EVENT_LEAVE = lv_conf.LV_EVENT_LEAVE;
/** Perform advanced hit-testing */
export const LV_EVENT_HIT_TEST = lv_conf.LV_EVENT_HIT_TEST;

/** Drawing events */
/** Check if the object fully covers an area. The event parameter is `lv_cover_check_info_t *`. */
export const LV_EVENT_COVER_CHECK = lv_conf.LV_EVENT_COVER_CHECK;
/** Get the required extra draw area around the object (e.g. for shadow). The event parameter is `lv_coord_t *` to store the size. */
export const LV_EVENT_REFR_EXT_DRAW_SIZE = lv_conf.LV_EVENT_REFR_EXT_DRAW_SIZE;
/** Starting the main drawing phase */
export const LV_EVENT_DRAW_MAIN_BEGIN = lv_conf.LV_EVENT_DRAW_MAIN_BEGIN;
/** Perform the main drawing */
export const LV_EVENT_DRAW_MAIN = lv_conf.LV_EVENT_DRAW_MAIN;
/** Finishing the main drawing phase */
export const LV_EVENT_DRAW_MAIN_END = lv_conf.LV_EVENT_DRAW_MAIN_END;
/** Starting the post draw phase (when all children are drawn) */
export const LV_EVENT_DRAW_POST_BEGIN = lv_conf.LV_EVENT_DRAW_POST_BEGIN;
/** Perform the post draw phase (when all children are drawn) */
export const LV_EVENT_DRAW_POST = lv_conf.LV_EVENT_DRAW_POST;
/** Finishing the post draw phase (when all children are drawn) */
export const LV_EVENT_DRAW_POST_END = lv_conf.LV_EVENT_DRAW_POST_END;
/** Starting to draw a part. The event parameter is `lv_obj_draw_dsc_t *`. */
export const LV_EVENT_DRAW_PART_BEGIN = lv_conf.LV_EVENT_DRAW_PART_BEGIN;
/** Finishing to draw a part. The event parameter is `lv_obj_draw_dsc_t *`. */
export const LV_EVENT_DRAW_PART_END = lv_conf.LV_EVENT_DRAW_PART_END;

/** Special events */
/** The object's value has changed (i.e. slider moved) */
export const LV_EVENT_VALUE_CHANGED = lv_conf.LV_EVENT_VALUE_CHANGED;
/** A text is inserted to the object. The event data is `char *` being inserted. */
export const LV_EVENT_INSERT = lv_conf.LV_EVENT_INSERT;
/** Notify the object to refresh something on it (for the user) */
export const LV_EVENT_REFRESH = lv_conf.LV_EVENT_REFRESH;
/** A process has finished */
export const LV_EVENT_READY = lv_conf.LV_EVENT_READY;
/** A process has been cancelled */
export const LV_EVENT_CANCEL = lv_conf.LV_EVENT_CANCEL;

/** Other events */
/** Object is being deleted */
export const LV_EVENT_DELETE = lv_conf.LV_EVENT_DELETE;
/** Child was removed, added, or its size, position were changed */
export const LV_EVENT_CHILD_CHANGED = lv_conf.LV_EVENT_CHILD_CHANGED;
/** Child was created, always bubbles up to all parents */
export const LV_EVENT_CHILD_CREATED = lv_conf.LV_EVENT_CHILD_CREATED;
/** Child was deleted, always bubbles up to all parents */
export const LV_EVENT_CHILD_DELETED = lv_conf.LV_EVENT_CHILD_DELETED;
/** A screen unload started, fired immediately when scr_load is called */
export const LV_EVENT_SCREEN_UNLOAD_START = lv_conf.LV_EVENT_SCREEN_UNLOAD_START;
/** A screen load started, fired when the screen change delay is expired */
export const LV_EVENT_SCREEN_LOAD_START = lv_conf.LV_EVENT_SCREEN_LOAD_START;
/** A screen was loaded */
export const LV_EVENT_SCREEN_LOADED = lv_conf.LV_EVENT_SCREEN_LOADED;
/** A screen was unloaded */
export const LV_EVENT_SCREEN_UNLOADED = lv_conf.LV_EVENT_SCREEN_UNLOADED;
/** Object coordinates/size have changed */
export const LV_EVENT_SIZE_CHANGED = lv_conf.LV_EVENT_SIZE_CHANGED;
/** Object's style has changed */
export const LV_EVENT_STYLE_CHANGED = lv_conf.LV_EVENT_STYLE_CHANGED;
/** The children position has changed due to a layout recalculation */
export const LV_EVENT_LAYOUT_CHANGED = lv_conf.LV_EVENT_LAYOUT_CHANGED;
/** Get the internal size of a widget */
export const LV_EVENT_GET_SELF_SIZE = lv_conf.LV_EVENT_GET_SELF_SIZE;

/** Number of default events */
export const LV_EVENT_LAST = lv_conf.LV_EVENT_LAST;

/**
 * This is a flag that can be set with an event so it's processed
 * before the class default event processing
 */
export const LV_EVENT_PREPROCESS = lv_conf.LV_EVENT_PREPROCESS;
// lv_event_code_t end - deps/lvgl/src/core/lv_event.h

// lv_arc_mode_t begin - deps/lvgl/src/widgets/lv_arc.h
export const LV_ARC_MODE_NORMAL = lv_conf.LV_ARC_MODE_NORMAL;
export const LV_ARC_MODE_SYMMETRICAL = lv_conf.LV_ARC_MODE_SYMMETRICAL;
export const LV_ARC_MODE_REVERSE = lv_conf.LV_ARC_MODE_REVERSE;
// lv_arc_mode_t end - deps/lvgl/src/widgets/lv_arc.h

// lv_chart_type_t begin - deps/lvgl/src/extra/widgets/chart/lv_chart.h
/** Don't draw the series */
export const LV_CHART_TYPE_NONE = lv_conf.LV_CHART_TYPE_NONE;
/** Connect the points with lines */
export const LV_CHART_TYPE_LINE = lv_conf.LV_CHART_TYPE_LINE;
/** Draw columns */
export const LV_CHART_TYPE_BAR = lv_conf.LV_CHART_TYPE_BAR;
/** Draw points and lines in 2D (x,y coordinates) */
export const LV_CHART_TYPE_SCATTER = lv_conf.LV_CHART_TYPE_SCATTER;
// lv_chart_type_t end - deps/lvgl/src/extra/widgets/chart/lv_chart.h

// lv_keyboard_mode_t begin - deps/lvgl/src/extra/widgets/keyboard/lv_keyboard.h
export const LV_KEYBOARD_MODE_TEXT_LOWER = lv_conf.LV_KEYBOARD_MODE_TEXT_LOWER;
export const LV_KEYBOARD_MODE_TEXT_UPPER = lv_conf.LV_KEYBOARD_MODE_TEXT_UPPER;
export const LV_KEYBOARD_MODE_SPECIAL = lv_conf.LV_KEYBOARD_MODE_SPECIAL;
export const LV_KEYBOARD_MODE_NUMBER = lv_conf.LV_KEYBOARD_MODE_NUMBER;
export const LV_KEYBOARD_MODE_USER_1 = lv_conf.LV_KEYBOARD_MODE_USER_1;
export const LV_KEYBOARD_MODE_USER_2 = lv_conf.LV_KEYBOARD_MODE_USER_2;
export const LV_KEYBOARD_MODE_USER_3 = lv_conf.LV_KEYBOARD_MODE_USER_3;
export const LV_KEYBOARD_MODE_USER_4 = lv_conf.LV_KEYBOARD_MODE_USER_4;
// lv_keyboard_mode_t end - deps/lvgl/src/extra/widgets/keyboard/lv_keyboard.h
