// Auto-generated by scripts/lv_conf_gen.py - do not edit by hand.
// Source: scripts/data/lv_conf_manifest.json

import * as lv_conf from "./lv_conf";

// PART_TYPE - deps/lvgl/src/core/lv_obj_style.h
/** LVGL lv_part_t with LV_ prefix stripped. */
export const PART_TYPE = {
  PART_MAIN: lv_conf.LV_PART_MAIN,
  PART_SCROLLBAR: lv_conf.LV_PART_SCROLLBAR,
  PART_INDICATOR: lv_conf.LV_PART_INDICATOR,
  PART_KNOB: lv_conf.LV_PART_KNOB,
  PART_SELECTED: lv_conf.LV_PART_SELECTED,
  PART_ITEMS: lv_conf.LV_PART_ITEMS,
  PART_CURSOR: lv_conf.LV_PART_CURSOR,
} as const;

// STATE_TYPE - deps/lvgl/src/core/lv_obj_style.h
/** LVGL lv_state_t with LV_ prefix stripped. */
export const STATE_TYPE = {
  STATE_DEFAULT: lv_conf.LV_STATE_DEFAULT,
  STATE_ALT: lv_conf.LV_STATE_ALT,
  STATE_CHECKED: lv_conf.LV_STATE_CHECKED,
  STATE_FOCUSED: lv_conf.LV_STATE_FOCUSED,
  STATE_FOCUS_KEY: lv_conf.LV_STATE_FOCUS_KEY,
  STATE_EDITED: lv_conf.LV_STATE_EDITED,
  STATE_HOVERED: lv_conf.LV_STATE_HOVERED,
  STATE_PRESSED: lv_conf.LV_STATE_PRESSED,
  STATE_SCROLLED: lv_conf.LV_STATE_SCROLLED,
  STATE_DISABLED: lv_conf.LV_STATE_DISABLED,
} as const;

// ALIGN_TYPE_MAP - deps/lvgl/src/misc/lv_area.h
/** LVGL lv_align_t values with LV_ prefix stripped for align / alignTo props. */
export const ALIGN_TYPE_MAP = {
  ALIGN_DEFAULT: lv_conf.LV_ALIGN_DEFAULT,
  ALIGN_TOP_LEFT: lv_conf.LV_ALIGN_TOP_LEFT,
  ALIGN_TOP_MID: lv_conf.LV_ALIGN_TOP_MID,
  ALIGN_TOP_RIGHT: lv_conf.LV_ALIGN_TOP_RIGHT,
  ALIGN_BOTTOM_LEFT: lv_conf.LV_ALIGN_BOTTOM_LEFT,
  ALIGN_BOTTOM_MID: lv_conf.LV_ALIGN_BOTTOM_MID,
  ALIGN_BOTTOM_RIGHT: lv_conf.LV_ALIGN_BOTTOM_RIGHT,
  ALIGN_LEFT_MID: lv_conf.LV_ALIGN_LEFT_MID,
  ALIGN_RIGHT_MID: lv_conf.LV_ALIGN_RIGHT_MID,
  ALIGN_CENTER: lv_conf.LV_ALIGN_CENTER,
  ALIGN_OUT_TOP_LEFT: lv_conf.LV_ALIGN_OUT_TOP_LEFT,
  ALIGN_OUT_TOP_MID: lv_conf.LV_ALIGN_OUT_TOP_MID,
  ALIGN_OUT_TOP_RIGHT: lv_conf.LV_ALIGN_OUT_TOP_RIGHT,
  ALIGN_OUT_BOTTOM_LEFT: lv_conf.LV_ALIGN_OUT_BOTTOM_LEFT,
  ALIGN_OUT_BOTTOM_MID: lv_conf.LV_ALIGN_OUT_BOTTOM_MID,
  ALIGN_OUT_BOTTOM_RIGHT: lv_conf.LV_ALIGN_OUT_BOTTOM_RIGHT,
  ALIGN_OUT_LEFT_TOP: lv_conf.LV_ALIGN_OUT_LEFT_TOP,
  ALIGN_OUT_LEFT_MID: lv_conf.LV_ALIGN_OUT_LEFT_MID,
  ALIGN_OUT_LEFT_BOTTOM: lv_conf.LV_ALIGN_OUT_LEFT_BOTTOM,
  ALIGN_OUT_RIGHT_TOP: lv_conf.LV_ALIGN_OUT_RIGHT_TOP,
  ALIGN_OUT_RIGHT_MID: lv_conf.LV_ALIGN_OUT_RIGHT_MID,
  ALIGN_OUT_RIGHT_BOTTOM: lv_conf.LV_ALIGN_OUT_RIGHT_BOTTOM,
} as const;

// LV_DIR_MAP - deps/lvgl/src/misc/lv_area.h
/** Scroll direction string -> LVGL lv_dir_t */
export const LV_DIR_MAP = {
  none: lv_conf.LV_DIR_NONE,
  left: lv_conf.LV_DIR_LEFT,
  right: lv_conf.LV_DIR_RIGHT,
  top: lv_conf.LV_DIR_TOP,
  bottom: lv_conf.LV_DIR_BOTTOM,
  horizontal: lv_conf.LV_DIR_HOR,
  vertical: lv_conf.LV_DIR_VER,
  all: lv_conf.LV_DIR_ALL,
} as const;

export type DirMapKey = keyof typeof LV_DIR_MAP;

// LV_FLEX_FLOW_MAP - deps/lvgl/src/layouts/flex/lv_flex.h
/** flex-direction + flex-wrap composite key -> LVGL lv_flex_flow_t */
export const LV_FLEX_FLOW_MAP = {
  row: lv_conf.LV_FLEX_FLOW_ROW,
  column: lv_conf.LV_FLEX_FLOW_COLUMN,
  row_wrap: lv_conf.LV_FLEX_FLOW_ROW_WRAP,
  row_reverse: lv_conf.LV_FLEX_FLOW_ROW_REVERSE,
  row_wrap_reverse: lv_conf.LV_FLEX_FLOW_ROW_WRAP_REVERSE,
  column_wrap: lv_conf.LV_FLEX_FLOW_COLUMN_WRAP,
  column_reverse: lv_conf.LV_FLEX_FLOW_COLUMN_REVERSE,
  column_wrap_reverse: lv_conf.LV_FLEX_FLOW_COLUMN_WRAP_REVERSE,
} as const;

export type FlexFlowMapKey = keyof typeof LV_FLEX_FLOW_MAP;

// LV_FLEX_ALIGN_MAP - deps/lvgl/src/layouts/flex/lv_flex.h
/** CSS flex alignment keyword -> LVGL lv_flex_align_t */
export const LV_FLEX_ALIGN_MAP = {
  "flex-start": lv_conf.LV_FLEX_ALIGN_START,
  "flex-end": lv_conf.LV_FLEX_ALIGN_END,
  center: lv_conf.LV_FLEX_ALIGN_CENTER,
  "space-evenly": lv_conf.LV_FLEX_ALIGN_SPACE_EVENLY,
  "space-around": lv_conf.LV_FLEX_ALIGN_SPACE_AROUND,
  "space-between": lv_conf.LV_FLEX_ALIGN_SPACE_BETWEEN,
} as const;

export type FlexAlignMapKey = keyof typeof LV_FLEX_ALIGN_MAP;

// LV_GRID_ALIGN_MAP - deps/lvgl/src/layouts/grid/lv_grid.h
/** CSS grid alignment keyword -> LVGL lv_grid_align_t */
export const LV_GRID_ALIGN_MAP = {
  start: lv_conf.LV_GRID_ALIGN_START,
  center: lv_conf.LV_GRID_ALIGN_CENTER,
  end: lv_conf.LV_GRID_ALIGN_END,
  stretch: lv_conf.LV_GRID_ALIGN_STRETCH,
  "space-evenly": lv_conf.LV_GRID_ALIGN_SPACE_EVENLY,
  "space-around": lv_conf.LV_GRID_ALIGN_SPACE_AROUND,
  "space-between": lv_conf.LV_GRID_ALIGN_SPACE_BETWEEN,
} as const;

export type GridAlignMapKey = keyof typeof LV_GRID_ALIGN_MAP;

// LV_SCROLL_SNAP_MAP - deps/lvgl/src/core/lv_obj_scroll.h
/** Scroll snap string -> LVGL lv_scroll_snap_t */
export const LV_SCROLL_SNAP_MAP = {
  none: lv_conf.LV_SCROLL_SNAP_NONE,
  snap_start: lv_conf.LV_SCROLL_SNAP_START,
  snap_end: lv_conf.LV_SCROLL_SNAP_END,
  snap_center: lv_conf.LV_SCROLL_SNAP_CENTER,
} as const;

export type ScrollSnapMapKey = keyof typeof LV_SCROLL_SNAP_MAP;

// LV_TEXT_ALIGN_MAP - deps/lvgl/src/misc/lv_text.h
/** text-align keyword -> LVGL lv_text_align_t */
export const LV_TEXT_ALIGN_MAP = {
  auto: lv_conf.LV_TEXT_ALIGN_AUTO,
  left: lv_conf.LV_TEXT_ALIGN_LEFT,
  center: lv_conf.LV_TEXT_ALIGN_CENTER,
  right: lv_conf.LV_TEXT_ALIGN_RIGHT,
} as const;

export type TextAlignMapKey = keyof typeof LV_TEXT_ALIGN_MAP;

// LV_TEXT_DECOR_MAP - deps/lvgl/src/misc/lv_style.h
/** text-decoration keyword -> LVGL lv_text_decor_t */
export const LV_TEXT_DECOR_MAP = {
  none: lv_conf.LV_TEXT_DECOR_NONE,
  underline: lv_conf.LV_TEXT_DECOR_UNDERLINE,
  strikethrough: lv_conf.LV_TEXT_DECOR_STRIKETHROUGH,
} as const;

export type TextDecorMapKey = keyof typeof LV_TEXT_DECOR_MAP;

// LV_GRAD_DIR_MAP - deps/lvgl/src/misc/lv_grad.h
/** background-grad-color-dir keyword -> LVGL lv_grad_dir_t */
export const LV_GRAD_DIR_MAP = {
  none: lv_conf.LV_GRAD_DIR_NONE,
  vertical: lv_conf.LV_GRAD_DIR_VER,
  horizontal: lv_conf.LV_GRAD_DIR_HOR,
  linear: lv_conf.LV_GRAD_DIR_LINEAR,
  radial: lv_conf.LV_GRAD_DIR_RADIAL,
  conical: lv_conf.LV_GRAD_DIR_CONICAL,
} as const;

export type GradDirMapKey = keyof typeof LV_GRAD_DIR_MAP;

// LV_LABEL_LONG_MODE_MAP - deps/lvgl/src/widgets/label/lv_label.h
/** text-overflow keyword -> LVGL lv_label_long_mode_t */
export const LV_LABEL_LONG_MODE_MAP = {
  auto: lv_conf.LV_LABEL_LONG_MODE_WRAP,
  ellipsis: lv_conf.LV_LABEL_LONG_MODE_DOTS,
  mode_scroll: lv_conf.LV_LABEL_LONG_MODE_SCROLL,
  circular: lv_conf.LV_LABEL_LONG_MODE_SCROLL_CIRCULAR,
  mode_clip: lv_conf.LV_LABEL_LONG_MODE_CLIP,
} as const;

export type LabelLongModeMapKey = keyof typeof LV_LABEL_LONG_MODE_MAP;

// EVENT_TYPE_MAP - deps/lvgl/src/misc/lv_event.h
/** EVENT_* names mapped to cached NativeRender.lv_conf values. */
export const EVENT_TYPE_MAP = {
  EVENT_ALL: lv_conf.LV_EVENT_ALL,

  /** Input device events */
  /** Widget has been pressed */
  EVENT_PRESSED: lv_conf.LV_EVENT_PRESSED,
  /** Widget is being pressed (sent continuously while pressing) */
  EVENT_PRESSING: lv_conf.LV_EVENT_PRESSING,
  /** Widget is still being pressed but slid cursor/finger off Widget */
  EVENT_PRESS_LOST: lv_conf.LV_EVENT_PRESS_LOST,
  /** Widget was pressed for a short period of time, then released. Not sent if scrolled. */
  EVENT_SHORT_CLICKED: lv_conf.LV_EVENT_SHORT_CLICKED,
  /** Sent for first short click within a small distance and short time */
  EVENT_SINGLE_CLICKED: lv_conf.LV_EVENT_SINGLE_CLICKED,
  /** Sent for second short click within small distance and short time */
  EVENT_DOUBLE_CLICKED: lv_conf.LV_EVENT_DOUBLE_CLICKED,
  /** Sent for third short click within small distance and short time */
  EVENT_TRIPLE_CLICKED: lv_conf.LV_EVENT_TRIPLE_CLICKED,
  /** Object has been pressed for at least `long_press_time`.  Not sent if scrolled. */
  EVENT_LONG_PRESSED: lv_conf.LV_EVENT_LONG_PRESSED,
  /** Sent after `long_press_time` in every `long_press_repeat_time` ms.  Not sent if scrolled. */
  EVENT_LONG_PRESSED_REPEAT: lv_conf.LV_EVENT_LONG_PRESSED_REPEAT,
  /** Sent on release if not scrolled (regardless to long press) */
  EVENT_CLICKED: lv_conf.LV_EVENT_CLICKED,
  /** Sent in every cases when Widget has been released */
  EVENT_RELEASED: lv_conf.LV_EVENT_RELEASED,
  /** Scrolling begins. The event parameter is a pointer to the animation of the scroll. Can be modified */
  EVENT_SCROLL_BEGIN: lv_conf.LV_EVENT_SCROLL_BEGIN,
  EVENT_SCROLL_THROW_BEGIN: lv_conf.LV_EVENT_SCROLL_THROW_BEGIN,
  /** Scrolling ends */
  EVENT_SCROLL_END: lv_conf.LV_EVENT_SCROLL_END,
  /** Scrolling */
  EVENT_SCROLL: lv_conf.LV_EVENT_SCROLL,
  /** A gesture is detected. Get gesture with `lv_indev_get_gesture_dir(lv_indev_active());` */
  EVENT_GESTURE: lv_conf.LV_EVENT_GESTURE,
  /** A key is sent to Widget. Get key with `lv_indev_get_key(lv_indev_active());` */
  EVENT_KEY: lv_conf.LV_EVENT_KEY,
  /** An encoder or wheel was rotated. Get rotation count with `lv_event_get_rotary_diff(e);` */
  EVENT_ROTARY: lv_conf.LV_EVENT_ROTARY,
  /** Widget received focus */
  EVENT_FOCUSED: lv_conf.LV_EVENT_FOCUSED,
  /** Widget's focus has been lost */
  EVENT_DEFOCUSED: lv_conf.LV_EVENT_DEFOCUSED,
  /** Widget's focus has been lost but is still selected */
  EVENT_LEAVE: lv_conf.LV_EVENT_LEAVE,
  /** Perform advanced hit-testing */
  EVENT_HIT_TEST: lv_conf.LV_EVENT_HIT_TEST,
  /** Indev has been reset */
  EVENT_INDEV_RESET: lv_conf.LV_EVENT_INDEV_RESET,
  /** Indev hover over object */
  EVENT_HOVER_OVER: lv_conf.LV_EVENT_HOVER_OVER,
  /** Indev hover leave object */
  EVENT_HOVER_LEAVE: lv_conf.LV_EVENT_HOVER_LEAVE,

  /** Drawing events */
  /** Check if Widget fully covers an area. The event parameter is `lv_cover_check_info_t *`. */
  EVENT_COVER_CHECK: lv_conf.LV_EVENT_COVER_CHECK,
  /** Get required extra draw area around Widget (e.g. for shadow). The event parameter is `int32_t *` to store the size. */
  EVENT_REFR_EXT_DRAW_SIZE: lv_conf.LV_EVENT_REFR_EXT_DRAW_SIZE,
  /** Starting the main drawing phase */
  EVENT_DRAW_MAIN_BEGIN: lv_conf.LV_EVENT_DRAW_MAIN_BEGIN,
  /** Perform the main drawing */
  EVENT_DRAW_MAIN: lv_conf.LV_EVENT_DRAW_MAIN,
  /** Finishing the main drawing phase */
  EVENT_DRAW_MAIN_END: lv_conf.LV_EVENT_DRAW_MAIN_END,
  /** Starting the post draw phase (when all children are drawn) */
  EVENT_DRAW_POST_BEGIN: lv_conf.LV_EVENT_DRAW_POST_BEGIN,
  /** Perform the post draw phase (when all children are drawn) */
  EVENT_DRAW_POST: lv_conf.LV_EVENT_DRAW_POST,
  /** Finishing the post draw phase (when all children are drawn) */
  EVENT_DRAW_POST_END: lv_conf.LV_EVENT_DRAW_POST_END,
  /** Adding a draw task. The `LV_OBJ_FLAG_SEND_DRAW_TASK_EVENTS` flag needs to be set */
  EVENT_DRAW_TASK_ADDED: lv_conf.LV_EVENT_DRAW_TASK_ADDED,

  /** Special events */
  /** Widget's value has changed (i.e. slider moved) */
  EVENT_VALUE_CHANGED: lv_conf.LV_EVENT_VALUE_CHANGED,
  /** Text has been inserted into Widget. The event data is `char *` being inserted. */
  EVENT_INSERT: lv_conf.LV_EVENT_INSERT,
  /** Notify Widget to refresh something on it (for user) */
  EVENT_REFRESH: lv_conf.LV_EVENT_REFRESH,
  /** A process has finished */
  EVENT_READY: lv_conf.LV_EVENT_READY,
  /** A process has been cancelled */
  EVENT_CANCEL: lv_conf.LV_EVENT_CANCEL,
  /** The state of the widget changed */
  EVENT_STATE_CHANGED: lv_conf.LV_EVENT_STATE_CHANGED,

  /** Other events */
  /** Object is being created */
  EVENT_CREATE: lv_conf.LV_EVENT_CREATE,
  /** Object is being deleted */
  EVENT_DELETE: lv_conf.LV_EVENT_DELETE,
  /** Child was removed, added, or its size, position were changed */
  EVENT_CHILD_CHANGED: lv_conf.LV_EVENT_CHILD_CHANGED,
  /** Child was created, always bubbles up to all parents */
  EVENT_CHILD_CREATED: lv_conf.LV_EVENT_CHILD_CREATED,
  /** Child was deleted, always bubbles up to all parents */
  EVENT_CHILD_DELETED: lv_conf.LV_EVENT_CHILD_DELETED,
  /** A screen unload started, fired immediately when scr_load is called */
  EVENT_SCREEN_UNLOAD_START: lv_conf.LV_EVENT_SCREEN_UNLOAD_START,
  /** A screen load started, fired when the screen change delay is expired */
  EVENT_SCREEN_LOAD_START: lv_conf.LV_EVENT_SCREEN_LOAD_START,
  /** A screen was loaded */
  EVENT_SCREEN_LOADED: lv_conf.LV_EVENT_SCREEN_LOADED,
  /** A screen was unloaded */
  EVENT_SCREEN_UNLOADED: lv_conf.LV_EVENT_SCREEN_UNLOADED,
  /** Object coordinates/size have changed */
  EVENT_SIZE_CHANGED: lv_conf.LV_EVENT_SIZE_CHANGED,
  /** Object's style has changed */
  EVENT_STYLE_CHANGED: lv_conf.LV_EVENT_STYLE_CHANGED,
  /** A child's position position has changed due to a layout recalculation */
  EVENT_LAYOUT_CHANGED: lv_conf.LV_EVENT_LAYOUT_CHANGED,
  /** Get internal size of a widget */
  EVENT_GET_SELF_SIZE: lv_conf.LV_EVENT_GET_SELF_SIZE,

  /** Events of optional LVGL components */
  /**
   * An area is invalidated (marked for redraw). `lv_event_get_param(e)`
   * returns a pointer to an `lv_area_t` object with the coordinates of the
   * area to be invalidated.  The area can be freely modified if needed to
   * adapt it a special requirement of the display. Usually needed with
   * monochrome displays to invalidate `N x 8` rows or columns in one pass.
   */
  EVENT_INVALIDATE_AREA: lv_conf.LV_EVENT_INVALIDATE_AREA,
  /** Sent when the resolution changes due to `lv_display_set_resolution()` or `lv_display_set_rotation()`. */
  EVENT_RESOLUTION_CHANGED: lv_conf.LV_EVENT_RESOLUTION_CHANGED,
  /** Sent as a result of any call to `lv_display_set_color_format()`. */
  EVENT_COLOR_FORMAT_CHANGED: lv_conf.LV_EVENT_COLOR_FORMAT_CHANGED,
  /** Sent when something happened that requires redraw. */
  EVENT_REFR_REQUEST: lv_conf.LV_EVENT_REFR_REQUEST,
  /** Sent before a refreshing cycle starts. Sent even if there is nothing to redraw. */
  EVENT_REFR_START: lv_conf.LV_EVENT_REFR_START,
  /** Sent when refreshing has been completed (after rendering and calling flush callback). Sent even if no redraw happened. */
  EVENT_REFR_READY: lv_conf.LV_EVENT_REFR_READY,
  /** Sent just before rendering begins. */
  EVENT_RENDER_START: lv_conf.LV_EVENT_RENDER_START,
  /** Sent after rendering has been completed. */
  EVENT_RENDER_READY: lv_conf.LV_EVENT_RENDER_READY,
  /** Sent before flush callback is called. */
  EVENT_FLUSH_START: lv_conf.LV_EVENT_FLUSH_START,
  /** Sent after flush callback call has returned. */
  EVENT_FLUSH_FINISH: lv_conf.LV_EVENT_FLUSH_FINISH,
  /** Sent before flush wait callback is called. */
  EVENT_FLUSH_WAIT_START: lv_conf.LV_EVENT_FLUSH_WAIT_START,
  /** Sent after flush wait callback call has returned. */
  EVENT_FLUSH_WAIT_FINISH: lv_conf.LV_EVENT_FLUSH_WAIT_FINISH,
  /** Sent after layout update completes */
  EVENT_UPDATE_LAYOUT_COMPLETED: lv_conf.LV_EVENT_UPDATE_LAYOUT_COMPLETED,

  EVENT_VSYNC: lv_conf.LV_EVENT_VSYNC,
  EVENT_VSYNC_REQUEST: lv_conf.LV_EVENT_VSYNC_REQUEST,
  /** Sent when the translation language changed. */
  EVENT_TRANSLATION_LANGUAGE_CHANGED: lv_conf.LV_EVENT_TRANSLATION_LANGUAGE_CHANGED,

  /** Number of default events */
  EVENT_LAST: lv_conf.LV_EVENT_LAST,

  /**
   * This is a flag that can be set with an event so it's processed
   * before the class default event processing
   */
  EVENT_PREPROCESS: lv_conf.LV_EVENT_PREPROCESS,
  EVENT_MARKED_DELETING: lv_conf.LV_EVENT_MARKED_DELETING,
} as const;

// ANIM_PATH - deps/lvgl/src/misc/lv_anim.h
/** LVGL lv_anim_path_cb_t index map for CSS transition-timing-function and animation easing. */
export const ANIM_PATH = {
  linear: 0,
  "ease-in": 1,
  "ease-out": 2,
  "ease-in-out": 3,
  overshoot: 4,
  bounce: 5,
  step: 6,
  "custom-bezier3": 7,
} as const;

export type AnimPathKey = keyof typeof ANIM_PATH;
