/* Auto-generated by scripts/lv_conf_gen.py - do not edit by hand. */
#pragma once

#include <lvgl.h>

/* LVGL lv_anim_path_cb_t index map for CSS transition-timing-function and animation easing. */
extern const lv_anim_path_cb_t lv_anim_path_funcs[];
extern const size_t LV_ANIM_PATH_COUNT;
