/* Auto-generated by scripts/lv_conf_gen.py - do not edit by hand. */

#include <lvgl.h>

/* LVGL lv_anim_path_cb_t index map for CSS transition-timing-function and animation easing. - deps/lvgl/src/misc/lv_anim.h */
extern const lv_anim_path_cb_t lv_anim_path_funcs[] = {
    &lv_anim_path_linear,
    &lv_anim_path_ease_in,
    &lv_anim_path_ease_out,
    &lv_anim_path_ease_in_out,
    &lv_anim_path_overshoot,
    &lv_anim_path_bounce,
    &lv_anim_path_step,
};

extern const size_t LV_ANIM_PATH_COUNT = sizeof(lv_anim_path_funcs) / sizeof(lv_anim_path_funcs[0]);
