/* Auto-generated by scripts/lv_conf_gen.py - do not edit by hand. */

#include "./lv_conf.hpp"

static void set_int_prop(JSContext* ctx, JSValue obj, const char* name, int32_t value) {
    JS_SetPropertyStr(ctx, obj, name, JS_NewInt32(ctx, value));
}

void Native_lv_conf_Init(JSContext* ctx, JSValue& ns) {
    JSValue obj = JS_NewObject(ctx);

    /* coord constants begin - deps/lvgl/src/misc/lv_area.h */
    set_int_prop(ctx, obj, "LV_COORD_MAX", LV_COORD_MAX);
    /* coord constants end - deps/lvgl/src/misc/lv_area.h */

    /* lv_part_t begin - deps/lvgl/src/core/lv_obj.h */
    /* A background like rectangle */
    set_int_prop(ctx, obj, "LV_PART_MAIN", LV_PART_MAIN);
    /* The scrollbar(s) */
    set_int_prop(ctx, obj, "LV_PART_SCROLLBAR", LV_PART_SCROLLBAR);
    /* Indicator, e.g. for slider, bar, switch, or the tick box of the checkbox */
    set_int_prop(ctx, obj, "LV_PART_INDICATOR", LV_PART_INDICATOR);
    /* Like handle to grab to adjust the value */
    set_int_prop(ctx, obj, "LV_PART_KNOB", LV_PART_KNOB);
    /* Indicate the currently selected option or section */
    set_int_prop(ctx, obj, "LV_PART_SELECTED", LV_PART_SELECTED);
    /* Used if the widget has multiple similar elements (e.g. table cells) */
    set_int_prop(ctx, obj, "LV_PART_ITEMS", LV_PART_ITEMS);
    /* Ticks on scale e.g. for a chart or meter */
    set_int_prop(ctx, obj, "LV_PART_TICKS", LV_PART_TICKS);
    /* Mark a specific place e.g. for text area's cursor or on a chart */
    set_int_prop(ctx, obj, "LV_PART_CURSOR", LV_PART_CURSOR);

    /* Extension point for custom widgets */
    set_int_prop(ctx, obj, "LV_PART_CUSTOM_FIRST", LV_PART_CUSTOM_FIRST);

    /* Special value can be used in some functions to target all parts */
    set_int_prop(ctx, obj, "LV_PART_ANY", LV_PART_ANY);
    /* lv_part_t end - deps/lvgl/src/core/lv_obj.h */

    /* lv_state_t begin - deps/lvgl/src/core/lv_obj.h */
    set_int_prop(ctx, obj, "LV_STATE_DEFAULT", LV_STATE_DEFAULT);
    set_int_prop(ctx, obj, "LV_STATE_CHECKED", LV_STATE_CHECKED);
    set_int_prop(ctx, obj, "LV_STATE_FOCUSED", LV_STATE_FOCUSED);
    set_int_prop(ctx, obj, "LV_STATE_FOCUS_KEY", LV_STATE_FOCUS_KEY);
    set_int_prop(ctx, obj, "LV_STATE_EDITED", LV_STATE_EDITED);
    set_int_prop(ctx, obj, "LV_STATE_HOVERED", LV_STATE_HOVERED);
    set_int_prop(ctx, obj, "LV_STATE_PRESSED", LV_STATE_PRESSED);
    set_int_prop(ctx, obj, "LV_STATE_SCROLLED", LV_STATE_SCROLLED);
    set_int_prop(ctx, obj, "LV_STATE_DISABLED", LV_STATE_DISABLED);

    set_int_prop(ctx, obj, "LV_STATE_USER_1", LV_STATE_USER_1);
    set_int_prop(ctx, obj, "LV_STATE_USER_2", LV_STATE_USER_2);
    set_int_prop(ctx, obj, "LV_STATE_USER_3", LV_STATE_USER_3);
    set_int_prop(ctx, obj, "LV_STATE_USER_4", LV_STATE_USER_4);

    /* Special value can be used in some functions to target all states */
    set_int_prop(ctx, obj, "LV_STATE_ANY", LV_STATE_ANY);
    /* lv_state_t end - deps/lvgl/src/core/lv_obj.h */

    /* lv_align_t begin - deps/lvgl/src/misc/lv_area.h */
    set_int_prop(ctx, obj, "LV_ALIGN_DEFAULT", LV_ALIGN_DEFAULT);
    set_int_prop(ctx, obj, "LV_ALIGN_TOP_LEFT", LV_ALIGN_TOP_LEFT);
    set_int_prop(ctx, obj, "LV_ALIGN_TOP_MID", LV_ALIGN_TOP_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_TOP_RIGHT", LV_ALIGN_TOP_RIGHT);
    set_int_prop(ctx, obj, "LV_ALIGN_BOTTOM_LEFT", LV_ALIGN_BOTTOM_LEFT);
    set_int_prop(ctx, obj, "LV_ALIGN_BOTTOM_MID", LV_ALIGN_BOTTOM_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_BOTTOM_RIGHT", LV_ALIGN_BOTTOM_RIGHT);
    set_int_prop(ctx, obj, "LV_ALIGN_LEFT_MID", LV_ALIGN_LEFT_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_RIGHT_MID", LV_ALIGN_RIGHT_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_CENTER", LV_ALIGN_CENTER);

    set_int_prop(ctx, obj, "LV_ALIGN_OUT_TOP_LEFT", LV_ALIGN_OUT_TOP_LEFT);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_TOP_MID", LV_ALIGN_OUT_TOP_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_TOP_RIGHT", LV_ALIGN_OUT_TOP_RIGHT);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_BOTTOM_LEFT", LV_ALIGN_OUT_BOTTOM_LEFT);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_BOTTOM_MID", LV_ALIGN_OUT_BOTTOM_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_BOTTOM_RIGHT", LV_ALIGN_OUT_BOTTOM_RIGHT);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_LEFT_TOP", LV_ALIGN_OUT_LEFT_TOP);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_LEFT_MID", LV_ALIGN_OUT_LEFT_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_LEFT_BOTTOM", LV_ALIGN_OUT_LEFT_BOTTOM);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_RIGHT_TOP", LV_ALIGN_OUT_RIGHT_TOP);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_RIGHT_MID", LV_ALIGN_OUT_RIGHT_MID);
    set_int_prop(ctx, obj, "LV_ALIGN_OUT_RIGHT_BOTTOM", LV_ALIGN_OUT_RIGHT_BOTTOM);
    /* lv_align_t end - deps/lvgl/src/misc/lv_area.h */

    /* lv_dir_t begin - deps/lvgl/src/misc/lv_area.h */
    set_int_prop(ctx, obj, "LV_DIR_NONE", LV_DIR_NONE);
    set_int_prop(ctx, obj, "LV_DIR_LEFT", LV_DIR_LEFT);
    set_int_prop(ctx, obj, "LV_DIR_RIGHT", LV_DIR_RIGHT);
    set_int_prop(ctx, obj, "LV_DIR_TOP", LV_DIR_TOP);
    set_int_prop(ctx, obj, "LV_DIR_BOTTOM", LV_DIR_BOTTOM);
    set_int_prop(ctx, obj, "LV_DIR_HOR", LV_DIR_HOR);
    set_int_prop(ctx, obj, "LV_DIR_VER", LV_DIR_VER);
    set_int_prop(ctx, obj, "LV_DIR_ALL", LV_DIR_ALL);
    /* lv_dir_t end - deps/lvgl/src/misc/lv_area.h */

    /* lv_flex_flow_t begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h */
#if LV_USE_FLEX
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_ROW", LV_FLEX_FLOW_ROW);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_COLUMN", LV_FLEX_FLOW_COLUMN);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_ROW_WRAP", LV_FLEX_FLOW_ROW_WRAP);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_ROW_REVERSE", LV_FLEX_FLOW_ROW_REVERSE);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_ROW_WRAP_REVERSE", LV_FLEX_FLOW_ROW_WRAP_REVERSE);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_COLUMN_WRAP", LV_FLEX_FLOW_COLUMN_WRAP);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_COLUMN_REVERSE", LV_FLEX_FLOW_COLUMN_REVERSE);
    set_int_prop(ctx, obj, "LV_FLEX_FLOW_COLUMN_WRAP_REVERSE", LV_FLEX_FLOW_COLUMN_WRAP_REVERSE);
#endif
    /* lv_flex_flow_t end - deps/lvgl/src/extra/layouts/flex/lv_flex.h */

    /* lv_flex_align_t begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h */
#if LV_USE_FLEX
    set_int_prop(ctx, obj, "LV_FLEX_ALIGN_START", LV_FLEX_ALIGN_START);
    set_int_prop(ctx, obj, "LV_FLEX_ALIGN_END", LV_FLEX_ALIGN_END);
    set_int_prop(ctx, obj, "LV_FLEX_ALIGN_CENTER", LV_FLEX_ALIGN_CENTER);
    set_int_prop(ctx, obj, "LV_FLEX_ALIGN_SPACE_EVENLY", LV_FLEX_ALIGN_SPACE_EVENLY);
    set_int_prop(ctx, obj, "LV_FLEX_ALIGN_SPACE_AROUND", LV_FLEX_ALIGN_SPACE_AROUND);
    set_int_prop(ctx, obj, "LV_FLEX_ALIGN_SPACE_BETWEEN", LV_FLEX_ALIGN_SPACE_BETWEEN);
#endif
    /* lv_flex_align_t end - deps/lvgl/src/extra/layouts/flex/lv_flex.h */

    /* lv_layout_flex begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h */
#if LV_USE_FLEX
    set_int_prop(ctx, obj, "LV_LAYOUT_FLEX", LV_LAYOUT_FLEX);
#endif
    /* lv_layout_flex end - deps/lvgl/src/extra/layouts/flex/lv_flex.h */

    /* lv_layout_grid begin - deps/lvgl/src/extra/layouts/grid/lv_grid.h */
#if LV_USE_GRID
    set_int_prop(ctx, obj, "LV_LAYOUT_GRID", LV_LAYOUT_GRID);
#endif
    /* lv_layout_grid end - deps/lvgl/src/extra/layouts/grid/lv_grid.h */

    /* lv_grid_align_t begin - deps/lvgl/src/extra/layouts/grid/lv_grid.h */
#if LV_USE_GRID
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_START", LV_GRID_ALIGN_START);
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_CENTER", LV_GRID_ALIGN_CENTER);
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_END", LV_GRID_ALIGN_END);
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_STRETCH", LV_GRID_ALIGN_STRETCH);
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_SPACE_EVENLY", LV_GRID_ALIGN_SPACE_EVENLY);
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_SPACE_AROUND", LV_GRID_ALIGN_SPACE_AROUND);
    set_int_prop(ctx, obj, "LV_GRID_ALIGN_SPACE_BETWEEN", LV_GRID_ALIGN_SPACE_BETWEEN);
#endif
    /* lv_grid_align_t end - deps/lvgl/src/extra/layouts/grid/lv_grid.h */

    /* lv_scroll_snap_t begin - deps/lvgl/src/core/lv_obj_scroll.h */
    /* Do not align, leave where it is */
    set_int_prop(ctx, obj, "LV_SCROLL_SNAP_NONE", LV_SCROLL_SNAP_NONE);
    /* Align to the left/top */
    set_int_prop(ctx, obj, "LV_SCROLL_SNAP_START", LV_SCROLL_SNAP_START);
    /* Align to the right/bottom */
    set_int_prop(ctx, obj, "LV_SCROLL_SNAP_END", LV_SCROLL_SNAP_END);
    /* Align to the center */
    set_int_prop(ctx, obj, "LV_SCROLL_SNAP_CENTER", LV_SCROLL_SNAP_CENTER);
    /* lv_scroll_snap_t end - deps/lvgl/src/core/lv_obj_scroll.h */

    /* lv_text_align_t begin - deps/lvgl/src/misc/lv_txt.h */
    /* Align text auto */
    set_int_prop(ctx, obj, "LV_TEXT_ALIGN_AUTO", LV_TEXT_ALIGN_AUTO);
    /* Align text to left */
    set_int_prop(ctx, obj, "LV_TEXT_ALIGN_LEFT", LV_TEXT_ALIGN_LEFT);
    /* Align text to center */
    set_int_prop(ctx, obj, "LV_TEXT_ALIGN_CENTER", LV_TEXT_ALIGN_CENTER);
    /* Align text to right */
    set_int_prop(ctx, obj, "LV_TEXT_ALIGN_RIGHT", LV_TEXT_ALIGN_RIGHT);
    /* lv_text_align_t end - deps/lvgl/src/misc/lv_txt.h */

    /* lv_text_decor_t begin - deps/lvgl/src/misc/lv_style.h */
    set_int_prop(ctx, obj, "LV_TEXT_DECOR_NONE", LV_TEXT_DECOR_NONE);
    set_int_prop(ctx, obj, "LV_TEXT_DECOR_UNDERLINE", LV_TEXT_DECOR_UNDERLINE);
    set_int_prop(ctx, obj, "LV_TEXT_DECOR_STRIKETHROUGH", LV_TEXT_DECOR_STRIKETHROUGH);
    /* lv_text_decor_t end - deps/lvgl/src/misc/lv_style.h */

    /* lv_grad_dir_t begin - deps/lvgl/src/misc/lv_style.h */
    /* No gradient (the `grad_color` property is ignored) */
    set_int_prop(ctx, obj, "LV_GRAD_DIR_NONE", LV_GRAD_DIR_NONE);
    /* Vertical (top to bottom) gradient */
    set_int_prop(ctx, obj, "LV_GRAD_DIR_VER", LV_GRAD_DIR_VER);
    /* Horizontal (left to right) gradient */
    set_int_prop(ctx, obj, "LV_GRAD_DIR_HOR", LV_GRAD_DIR_HOR);
    /* lv_grad_dir_t end - deps/lvgl/src/misc/lv_style.h */

    /* lv_border_side_t begin - deps/lvgl/src/misc/lv_style.h */
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_NONE", LV_BORDER_SIDE_NONE);
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_BOTTOM", LV_BORDER_SIDE_BOTTOM);
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_TOP", LV_BORDER_SIDE_TOP);
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_LEFT", LV_BORDER_SIDE_LEFT);
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_RIGHT", LV_BORDER_SIDE_RIGHT);
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_FULL", LV_BORDER_SIDE_FULL);
    /* FOR matrix-like objects (e.g. Button matrix) */
    set_int_prop(ctx, obj, "LV_BORDER_SIDE_INTERNAL", LV_BORDER_SIDE_INTERNAL);
    /* lv_border_side_t end - deps/lvgl/src/misc/lv_style.h */

    /* lv_label_long_mode_t begin - deps/lvgl/src/widgets/lv_label.h */
    /* Keep the object width, wrap the too long lines and expand the object height */
    set_int_prop(ctx, obj, "LV_LABEL_LONG_WRAP", LV_LABEL_LONG_WRAP);
    /* Keep the size and write dots at the end if the text is too long */
    set_int_prop(ctx, obj, "LV_LABEL_LONG_DOT", LV_LABEL_LONG_DOT);
    /* Keep the size and roll the text back and forth */
    set_int_prop(ctx, obj, "LV_LABEL_LONG_SCROLL", LV_LABEL_LONG_SCROLL);
    /* Keep the size and roll the text circularly */
    set_int_prop(ctx, obj, "LV_LABEL_LONG_SCROLL_CIRCULAR", LV_LABEL_LONG_SCROLL_CIRCULAR);
    /* Keep the size and clip the text out of it */
    set_int_prop(ctx, obj, "LV_LABEL_LONG_CLIP", LV_LABEL_LONG_CLIP);
    /* lv_label_long_mode_t end - deps/lvgl/src/widgets/lv_label.h */

    /* lv_style_prop_meta begin - deps/lvgl/src/misc/lv_style.h */
    set_int_prop(ctx, obj, "LV_STYLE_PROP_FLAG_NONE", LV_STYLE_PROP_FLAG_NONE);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_INHERIT", LV_STYLE_PROP_INHERIT);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_EXT_DRAW", LV_STYLE_PROP_EXT_DRAW);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_LAYOUT_REFR", LV_STYLE_PROP_LAYOUT_REFR);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_PARENT_LAYOUT_REFR", LV_STYLE_PROP_PARENT_LAYOUT_REFR);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_LAYER_REFR", LV_STYLE_PROP_LAYER_REFR);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_ALL", LV_STYLE_PROP_ALL);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_META_INHERIT", LV_STYLE_PROP_META_INHERIT);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_META_INITIAL", LV_STYLE_PROP_META_INITIAL);
    set_int_prop(ctx, obj, "LV_STYLE_PROP_META_MASK", LV_STYLE_PROP_META_MASK);
    /* lv_style_prop_meta end - deps/lvgl/src/misc/lv_style.h */

    /* lv_style_prop_t begin - deps/lvgl/src/misc/lv_style.h */
    set_int_prop(ctx, obj, "LV_STYLE_PROP_INV", LV_STYLE_PROP_INV);

    /* Group 0 */
    set_int_prop(ctx, obj, "LV_STYLE_WIDTH", LV_STYLE_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_MIN_WIDTH", LV_STYLE_MIN_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_MAX_WIDTH", LV_STYLE_MAX_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_HEIGHT", LV_STYLE_HEIGHT);
    set_int_prop(ctx, obj, "LV_STYLE_MIN_HEIGHT", LV_STYLE_MIN_HEIGHT);
    set_int_prop(ctx, obj, "LV_STYLE_MAX_HEIGHT", LV_STYLE_MAX_HEIGHT);
    set_int_prop(ctx, obj, "LV_STYLE_X", LV_STYLE_X);
    set_int_prop(ctx, obj, "LV_STYLE_Y", LV_STYLE_Y);
    set_int_prop(ctx, obj, "LV_STYLE_ALIGN", LV_STYLE_ALIGN);
    set_int_prop(ctx, obj, "LV_STYLE_LAYOUT", LV_STYLE_LAYOUT);
    set_int_prop(ctx, obj, "LV_STYLE_RADIUS", LV_STYLE_RADIUS);

    /* Group 1 */
    set_int_prop(ctx, obj, "LV_STYLE_PAD_TOP", LV_STYLE_PAD_TOP);
    set_int_prop(ctx, obj, "LV_STYLE_PAD_BOTTOM", LV_STYLE_PAD_BOTTOM);
    set_int_prop(ctx, obj, "LV_STYLE_PAD_LEFT", LV_STYLE_PAD_LEFT);
    set_int_prop(ctx, obj, "LV_STYLE_PAD_RIGHT", LV_STYLE_PAD_RIGHT);
    set_int_prop(ctx, obj, "LV_STYLE_PAD_ROW", LV_STYLE_PAD_ROW);
    set_int_prop(ctx, obj, "LV_STYLE_PAD_COLUMN", LV_STYLE_PAD_COLUMN);
    set_int_prop(ctx, obj, "LV_STYLE_BASE_DIR", LV_STYLE_BASE_DIR);
    set_int_prop(ctx, obj, "LV_STYLE_CLIP_CORNER", LV_STYLE_CLIP_CORNER);

    /* Group 2 */
    set_int_prop(ctx, obj, "LV_STYLE_BG_COLOR", LV_STYLE_BG_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_BG_OPA", LV_STYLE_BG_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_BG_GRAD_COLOR", LV_STYLE_BG_GRAD_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_BG_GRAD_DIR", LV_STYLE_BG_GRAD_DIR);
    set_int_prop(ctx, obj, "LV_STYLE_BG_MAIN_STOP", LV_STYLE_BG_MAIN_STOP);
    set_int_prop(ctx, obj, "LV_STYLE_BG_GRAD_STOP", LV_STYLE_BG_GRAD_STOP);
    set_int_prop(ctx, obj, "LV_STYLE_BG_GRAD", LV_STYLE_BG_GRAD);
    set_int_prop(ctx, obj, "LV_STYLE_BG_DITHER_MODE", LV_STYLE_BG_DITHER_MODE);
    set_int_prop(ctx, obj, "LV_STYLE_BG_IMG_SRC", LV_STYLE_BG_IMG_SRC);
    set_int_prop(ctx, obj, "LV_STYLE_BG_IMG_OPA", LV_STYLE_BG_IMG_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_BG_IMG_RECOLOR", LV_STYLE_BG_IMG_RECOLOR);
    set_int_prop(ctx, obj, "LV_STYLE_BG_IMG_RECOLOR_OPA", LV_STYLE_BG_IMG_RECOLOR_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_BG_IMG_TILED", LV_STYLE_BG_IMG_TILED);

    /* Group 3 */
    set_int_prop(ctx, obj, "LV_STYLE_BORDER_COLOR", LV_STYLE_BORDER_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_BORDER_OPA", LV_STYLE_BORDER_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_BORDER_WIDTH", LV_STYLE_BORDER_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_BORDER_SIDE", LV_STYLE_BORDER_SIDE);
    set_int_prop(ctx, obj, "LV_STYLE_BORDER_POST", LV_STYLE_BORDER_POST);
    set_int_prop(ctx, obj, "LV_STYLE_OUTLINE_WIDTH", LV_STYLE_OUTLINE_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_OUTLINE_COLOR", LV_STYLE_OUTLINE_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_OUTLINE_OPA", LV_STYLE_OUTLINE_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_OUTLINE_PAD", LV_STYLE_OUTLINE_PAD);

    /* Group 4 */
    set_int_prop(ctx, obj, "LV_STYLE_SHADOW_WIDTH", LV_STYLE_SHADOW_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_SHADOW_OFS_X", LV_STYLE_SHADOW_OFS_X);
    set_int_prop(ctx, obj, "LV_STYLE_SHADOW_OFS_Y", LV_STYLE_SHADOW_OFS_Y);
    set_int_prop(ctx, obj, "LV_STYLE_SHADOW_SPREAD", LV_STYLE_SHADOW_SPREAD);
    set_int_prop(ctx, obj, "LV_STYLE_SHADOW_COLOR", LV_STYLE_SHADOW_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_SHADOW_OPA", LV_STYLE_SHADOW_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_IMG_OPA", LV_STYLE_IMG_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_IMG_RECOLOR", LV_STYLE_IMG_RECOLOR);
    set_int_prop(ctx, obj, "LV_STYLE_IMG_RECOLOR_OPA", LV_STYLE_IMG_RECOLOR_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_LINE_WIDTH", LV_STYLE_LINE_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_LINE_DASH_WIDTH", LV_STYLE_LINE_DASH_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_LINE_DASH_GAP", LV_STYLE_LINE_DASH_GAP);
    set_int_prop(ctx, obj, "LV_STYLE_LINE_ROUNDED", LV_STYLE_LINE_ROUNDED);
    set_int_prop(ctx, obj, "LV_STYLE_LINE_COLOR", LV_STYLE_LINE_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_LINE_OPA", LV_STYLE_LINE_OPA);

    /* Group 5 */
    set_int_prop(ctx, obj, "LV_STYLE_ARC_WIDTH", LV_STYLE_ARC_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_ARC_ROUNDED", LV_STYLE_ARC_ROUNDED);
    set_int_prop(ctx, obj, "LV_STYLE_ARC_COLOR", LV_STYLE_ARC_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_ARC_OPA", LV_STYLE_ARC_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_ARC_IMG_SRC", LV_STYLE_ARC_IMG_SRC);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_COLOR", LV_STYLE_TEXT_COLOR);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_OPA", LV_STYLE_TEXT_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_FONT", LV_STYLE_TEXT_FONT);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_LETTER_SPACE", LV_STYLE_TEXT_LETTER_SPACE);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_LINE_SPACE", LV_STYLE_TEXT_LINE_SPACE);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_DECOR", LV_STYLE_TEXT_DECOR);
    set_int_prop(ctx, obj, "LV_STYLE_TEXT_ALIGN", LV_STYLE_TEXT_ALIGN);

    /* Group 6 */
    set_int_prop(ctx, obj, "LV_STYLE_OPA", LV_STYLE_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_COLOR_FILTER_DSC", LV_STYLE_COLOR_FILTER_DSC);
    set_int_prop(ctx, obj, "LV_STYLE_COLOR_FILTER_OPA", LV_STYLE_COLOR_FILTER_OPA);
    set_int_prop(ctx, obj, "LV_STYLE_ANIM", LV_STYLE_ANIM);
    set_int_prop(ctx, obj, "LV_STYLE_ANIM_TIME", LV_STYLE_ANIM_TIME);
    set_int_prop(ctx, obj, "LV_STYLE_ANIM_SPEED", LV_STYLE_ANIM_SPEED);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSITION", LV_STYLE_TRANSITION);
    set_int_prop(ctx, obj, "LV_STYLE_BLEND_MODE", LV_STYLE_BLEND_MODE);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSFORM_WIDTH", LV_STYLE_TRANSFORM_WIDTH);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSFORM_HEIGHT", LV_STYLE_TRANSFORM_HEIGHT);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSLATE_X", LV_STYLE_TRANSLATE_X);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSLATE_Y", LV_STYLE_TRANSLATE_Y);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSFORM_ZOOM", LV_STYLE_TRANSFORM_ZOOM);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSFORM_ANGLE", LV_STYLE_TRANSFORM_ANGLE);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSFORM_PIVOT_X", LV_STYLE_TRANSFORM_PIVOT_X);
    set_int_prop(ctx, obj, "LV_STYLE_TRANSFORM_PIVOT_Y", LV_STYLE_TRANSFORM_PIVOT_Y);

    set_int_prop(ctx, obj, "LV_STYLE_LAST_BUILT_IN_PROP", _LV_STYLE_LAST_BUILT_IN_PROP);
    set_int_prop(ctx, obj, "LV_STYLE_NUM_BUILT_IN_PROPS", _LV_STYLE_NUM_BUILT_IN_PROPS);

    set_int_prop(ctx, obj, "LV_STYLE_PROP_ANY", LV_STYLE_PROP_ANY);
    /* lv_style_prop_t end - deps/lvgl/src/misc/lv_style.h */

    /* lv_style_prop_t_extend_flow begin - deps/lvgl/src/extra/layouts/flex/lv_flex.h */
#if LV_USE_FLEX
    set_int_prop(ctx, obj, "LV_STYLE_FLEX_FLOW", LV_STYLE_FLEX_FLOW);
    set_int_prop(ctx, obj, "LV_STYLE_FLEX_MAIN_PLACE", LV_STYLE_FLEX_MAIN_PLACE);
    set_int_prop(ctx, obj, "LV_STYLE_FLEX_CROSS_PLACE", LV_STYLE_FLEX_CROSS_PLACE);
    set_int_prop(ctx, obj, "LV_STYLE_FLEX_TRACK_PLACE", LV_STYLE_FLEX_TRACK_PLACE);
    set_int_prop(ctx, obj, "LV_STYLE_FLEX_GROW", LV_STYLE_FLEX_GROW);
#endif
    /* lv_style_prop_t_extend_flow end - deps/lvgl/src/extra/layouts/flex/lv_flex.h */

    /* lv_style_prop_t_extend_grid begin - deps/lvgl/src/extra/layouts/grid/lv_grid.h */
#if LV_USE_GRID
    set_int_prop(ctx, obj, "LV_STYLE_GRID_COLUMN_DSC_ARRAY", LV_STYLE_GRID_COLUMN_DSC_ARRAY);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_COLUMN_ALIGN", LV_STYLE_GRID_COLUMN_ALIGN);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_ROW_DSC_ARRAY", LV_STYLE_GRID_ROW_DSC_ARRAY);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_ROW_ALIGN", LV_STYLE_GRID_ROW_ALIGN);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_CELL_COLUMN_POS", LV_STYLE_GRID_CELL_COLUMN_POS);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_CELL_COLUMN_SPAN", LV_STYLE_GRID_CELL_COLUMN_SPAN);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_CELL_X_ALIGN", LV_STYLE_GRID_CELL_X_ALIGN);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_CELL_ROW_POS", LV_STYLE_GRID_CELL_ROW_POS);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_CELL_ROW_SPAN", LV_STYLE_GRID_CELL_ROW_SPAN);
    set_int_prop(ctx, obj, "LV_STYLE_GRID_CELL_Y_ALIGN", LV_STYLE_GRID_CELL_Y_ALIGN);
#endif
    /* lv_style_prop_t_extend_grid end - deps/lvgl/src/extra/layouts/grid/lv_grid.h */

    /* lv_style_prop_t_extend_css begin - src/render/native/core/lv_conf/lv_style_prop_extend.h */
    set_int_prop(ctx, obj, "LV_STYLE_CSS_CHART_SCALE_X", LV_STYLE_CSS_CHART_SCALE_X);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_CHART_SCALE_Y", LV_STYLE_CSS_CHART_SCALE_Y);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_DISPLAY", LV_STYLE_CSS_DISPLAY);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_FLEX_ALIGN", LV_STYLE_CSS_FLEX_ALIGN);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_GRID_ALIGN", LV_STYLE_CSS_GRID_ALIGN);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_GRID_CHILD", LV_STYLE_CSS_GRID_CHILD);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_GRID_TEMPLATE", LV_STYLE_CSS_GRID_TEMPLATE);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_IMG_ORIGIN", LV_STYLE_CSS_IMG_ORIGIN);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_IMG_ROTATE", LV_STYLE_CSS_IMG_ROTATE);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_IMG_SCALE", LV_STYLE_CSS_IMG_SCALE);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_OVERFLOW", LV_STYLE_CSS_OVERFLOW);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_OVERFLOW_SCROLLING", LV_STYLE_CSS_OVERFLOW_SCROLLING);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_POSITION", LV_STYLE_CSS_POSITION);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_SCROLL_ENABLE_SNAP", LV_STYLE_CSS_SCROLL_ENABLE_SNAP);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_SCROLL_SNAP_X", LV_STYLE_CSS_SCROLL_SNAP_X);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_SCROLL_SNAP_Y", LV_STYLE_CSS_SCROLL_SNAP_Y);
    set_int_prop(ctx, obj, "LV_STYLE_CSS_TEXT_OVERFLOW", LV_STYLE_CSS_TEXT_OVERFLOW);
    /* lv_style_prop_t_extend_css end - src/render/native/core/lv_conf/lv_style_prop_extend.h */

    /* lv_event_code_t begin - deps/lvgl/src/core/lv_event.h */
    set_int_prop(ctx, obj, "LV_EVENT_ALL", LV_EVENT_ALL);

    /* Input device events */
    /* The object has been pressed */
    set_int_prop(ctx, obj, "LV_EVENT_PRESSED", LV_EVENT_PRESSED);
    /* The object is being pressed (called continuously while pressing) */
    set_int_prop(ctx, obj, "LV_EVENT_PRESSING", LV_EVENT_PRESSING);
    /* The object is still being pressed but slid cursor/finger off of the object */
    set_int_prop(ctx, obj, "LV_EVENT_PRESS_LOST", LV_EVENT_PRESS_LOST);
    /* The object was pressed for a short period of time, then released it. Not called if scrolled. */
    set_int_prop(ctx, obj, "LV_EVENT_SHORT_CLICKED", LV_EVENT_SHORT_CLICKED);
    /* Object has been pressed for at least `long_press_time`.  Not called if scrolled. */
    set_int_prop(ctx, obj, "LV_EVENT_LONG_PRESSED", LV_EVENT_LONG_PRESSED);
    /* Called after `long_press_time` in every `long_press_repeat_time` ms.  Not called if scrolled. */
    set_int_prop(ctx, obj, "LV_EVENT_LONG_PRESSED_REPEAT", LV_EVENT_LONG_PRESSED_REPEAT);
    /* Called on release if not scrolled (regardless to long press) */
    set_int_prop(ctx, obj, "LV_EVENT_CLICKED", LV_EVENT_CLICKED);
    /* Called in every cases when the object has been released */
    set_int_prop(ctx, obj, "LV_EVENT_RELEASED", LV_EVENT_RELEASED);
    /* Scrolling begins. The event parameter is a pointer to the animation of the scroll. Can be modified */
    set_int_prop(ctx, obj, "LV_EVENT_SCROLL_BEGIN", LV_EVENT_SCROLL_BEGIN);
    /* Scrolling ends */
    set_int_prop(ctx, obj, "LV_EVENT_SCROLL_END", LV_EVENT_SCROLL_END);
    /* Scrolling */
    set_int_prop(ctx, obj, "LV_EVENT_SCROLL", LV_EVENT_SCROLL);
    /* A gesture is detected. Get the gesture with `lv_indev_get_gesture_dir(lv_indev_get_act());` */
    set_int_prop(ctx, obj, "LV_EVENT_GESTURE", LV_EVENT_GESTURE);
    /* A key is sent to the object. Get the key with `lv_indev_get_key(lv_indev_get_act());` */
    set_int_prop(ctx, obj, "LV_EVENT_KEY", LV_EVENT_KEY);
    /* The object is focused */
    set_int_prop(ctx, obj, "LV_EVENT_FOCUSED", LV_EVENT_FOCUSED);
    /* The object is defocused */
    set_int_prop(ctx, obj, "LV_EVENT_DEFOCUSED", LV_EVENT_DEFOCUSED);
    /* The object is defocused but still selected */
    set_int_prop(ctx, obj, "LV_EVENT_LEAVE", LV_EVENT_LEAVE);
    /* Perform advanced hit-testing */
    set_int_prop(ctx, obj, "LV_EVENT_HIT_TEST", LV_EVENT_HIT_TEST);

    /* Drawing events */
    /* Check if the object fully covers an area. The event parameter is `lv_cover_check_info_t *`. */
    set_int_prop(ctx, obj, "LV_EVENT_COVER_CHECK", LV_EVENT_COVER_CHECK);
    /* Get the required extra draw area around the object (e.g. for shadow). The event parameter is `lv_coord_t *` to store the size. */
    set_int_prop(ctx, obj, "LV_EVENT_REFR_EXT_DRAW_SIZE", LV_EVENT_REFR_EXT_DRAW_SIZE);
    /* Starting the main drawing phase */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_MAIN_BEGIN", LV_EVENT_DRAW_MAIN_BEGIN);
    /* Perform the main drawing */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_MAIN", LV_EVENT_DRAW_MAIN);
    /* Finishing the main drawing phase */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_MAIN_END", LV_EVENT_DRAW_MAIN_END);
    /* Starting the post draw phase (when all children are drawn) */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_POST_BEGIN", LV_EVENT_DRAW_POST_BEGIN);
    /* Perform the post draw phase (when all children are drawn) */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_POST", LV_EVENT_DRAW_POST);
    /* Finishing the post draw phase (when all children are drawn) */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_POST_END", LV_EVENT_DRAW_POST_END);
    /* Starting to draw a part. The event parameter is `lv_obj_draw_dsc_t *`. */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_PART_BEGIN", LV_EVENT_DRAW_PART_BEGIN);
    /* Finishing to draw a part. The event parameter is `lv_obj_draw_dsc_t *`. */
    set_int_prop(ctx, obj, "LV_EVENT_DRAW_PART_END", LV_EVENT_DRAW_PART_END);

    /* Special events */
    /* The object's value has changed (i.e. slider moved) */
    set_int_prop(ctx, obj, "LV_EVENT_VALUE_CHANGED", LV_EVENT_VALUE_CHANGED);
    /* A text is inserted to the object. The event data is `char *` being inserted. */
    set_int_prop(ctx, obj, "LV_EVENT_INSERT", LV_EVENT_INSERT);
    /* Notify the object to refresh something on it (for the user) */
    set_int_prop(ctx, obj, "LV_EVENT_REFRESH", LV_EVENT_REFRESH);
    /* A process has finished */
    set_int_prop(ctx, obj, "LV_EVENT_READY", LV_EVENT_READY);
    /* A process has been cancelled */
    set_int_prop(ctx, obj, "LV_EVENT_CANCEL", LV_EVENT_CANCEL);

    /* Other events */
    /* Object is being deleted */
    set_int_prop(ctx, obj, "LV_EVENT_DELETE", LV_EVENT_DELETE);
    /* Child was removed, added, or its size, position were changed */
    set_int_prop(ctx, obj, "LV_EVENT_CHILD_CHANGED", LV_EVENT_CHILD_CHANGED);
    /* Child was created, always bubbles up to all parents */
    set_int_prop(ctx, obj, "LV_EVENT_CHILD_CREATED", LV_EVENT_CHILD_CREATED);
    /* Child was deleted, always bubbles up to all parents */
    set_int_prop(ctx, obj, "LV_EVENT_CHILD_DELETED", LV_EVENT_CHILD_DELETED);
    /* A screen unload started, fired immediately when scr_load is called */
    set_int_prop(ctx, obj, "LV_EVENT_SCREEN_UNLOAD_START", LV_EVENT_SCREEN_UNLOAD_START);
    /* A screen load started, fired when the screen change delay is expired */
    set_int_prop(ctx, obj, "LV_EVENT_SCREEN_LOAD_START", LV_EVENT_SCREEN_LOAD_START);
    /* A screen was loaded */
    set_int_prop(ctx, obj, "LV_EVENT_SCREEN_LOADED", LV_EVENT_SCREEN_LOADED);
    /* A screen was unloaded */
    set_int_prop(ctx, obj, "LV_EVENT_SCREEN_UNLOADED", LV_EVENT_SCREEN_UNLOADED);
    /* Object coordinates/size have changed */
    set_int_prop(ctx, obj, "LV_EVENT_SIZE_CHANGED", LV_EVENT_SIZE_CHANGED);
    /* Object's style has changed */
    set_int_prop(ctx, obj, "LV_EVENT_STYLE_CHANGED", LV_EVENT_STYLE_CHANGED);
    /* The children position has changed due to a layout recalculation */
    set_int_prop(ctx, obj, "LV_EVENT_LAYOUT_CHANGED", LV_EVENT_LAYOUT_CHANGED);
    /* Get the internal size of a widget */
    set_int_prop(ctx, obj, "LV_EVENT_GET_SELF_SIZE", LV_EVENT_GET_SELF_SIZE);

    /* Number of default events */
    set_int_prop(ctx, obj, "LV_EVENT_LAST", _LV_EVENT_LAST);

    /*
     * This is a flag that can be set with an event so it's processed
     * before the class default event processing
     */
    set_int_prop(ctx, obj, "LV_EVENT_PREPROCESS", LV_EVENT_PREPROCESS);
    /* lv_event_code_t end - deps/lvgl/src/core/lv_event.h */

    /* lv_arc_mode_t begin - deps/lvgl/src/widgets/lv_arc.h */
#if LV_USE_ARC
    set_int_prop(ctx, obj, "LV_ARC_MODE_NORMAL", LV_ARC_MODE_NORMAL);
    set_int_prop(ctx, obj, "LV_ARC_MODE_SYMMETRICAL", LV_ARC_MODE_SYMMETRICAL);
    set_int_prop(ctx, obj, "LV_ARC_MODE_REVERSE", LV_ARC_MODE_REVERSE);
#endif
    /* lv_arc_mode_t end - deps/lvgl/src/widgets/lv_arc.h */

    /* lv_chart_type_t begin - deps/lvgl/src/extra/widgets/chart/lv_chart.h */
#if LV_USE_CHART
    /* Don't draw the series */
    set_int_prop(ctx, obj, "LV_CHART_TYPE_NONE", LV_CHART_TYPE_NONE);
    /* Connect the points with lines */
    set_int_prop(ctx, obj, "LV_CHART_TYPE_LINE", LV_CHART_TYPE_LINE);
    /* Draw columns */
    set_int_prop(ctx, obj, "LV_CHART_TYPE_BAR", LV_CHART_TYPE_BAR);
    /* Draw points and lines in 2D (x,y coordinates) */
    set_int_prop(ctx, obj, "LV_CHART_TYPE_SCATTER", LV_CHART_TYPE_SCATTER);
#endif
    /* lv_chart_type_t end - deps/lvgl/src/extra/widgets/chart/lv_chart.h */

    /* lv_keyboard_mode_t begin - deps/lvgl/src/extra/widgets/keyboard/lv_keyboard.h */
#if LV_USE_KEYBOARD
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_TEXT_LOWER", LV_KEYBOARD_MODE_TEXT_LOWER);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_TEXT_UPPER", LV_KEYBOARD_MODE_TEXT_UPPER);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_SPECIAL", LV_KEYBOARD_MODE_SPECIAL);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_NUMBER", LV_KEYBOARD_MODE_NUMBER);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_USER_1", LV_KEYBOARD_MODE_USER_1);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_USER_2", LV_KEYBOARD_MODE_USER_2);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_USER_3", LV_KEYBOARD_MODE_USER_3);
    set_int_prop(ctx, obj, "LV_KEYBOARD_MODE_USER_4", LV_KEYBOARD_MODE_USER_4);
#endif
    /* lv_keyboard_mode_t end - deps/lvgl/src/extra/widgets/keyboard/lv_keyboard.h */
    JS_SetPropertyStr(ctx, ns, "lv_conf", obj);
}
