/**
 * Virtual lv_style_prop_t ids for CSS handler batch dispatch.
 * Not registered with LVGL style storage and must not be passed to lv_style_set_prop.
 * Registered at runtime via lvgljs_style_css_prop_init (see lv_style_prop_extend.cpp).
 * Auto-generated by scripts/lv_conf_gen.py - do not edit by hand.
 */
#ifndef LVGLJS_LV_STYLE_PROP_EXTEND_H
#define LVGLJS_LV_STYLE_PROP_EXTEND_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

extern lv_style_prop_t LV_STYLE_CSS_CHART_SCALE_X;
extern lv_style_prop_t LV_STYLE_CSS_CHART_SCALE_Y;
extern lv_style_prop_t LV_STYLE_CSS_DISPLAY;
extern lv_style_prop_t LV_STYLE_CSS_FLEX_ALIGN;
extern lv_style_prop_t LV_STYLE_CSS_GRID_ALIGN;
extern lv_style_prop_t LV_STYLE_CSS_GRID_CHILD;
extern lv_style_prop_t LV_STYLE_CSS_GRID_TEMPLATE;
extern lv_style_prop_t LV_STYLE_CSS_IMG_ORIGIN;
extern lv_style_prop_t LV_STYLE_CSS_IMG_ROTATE;
extern lv_style_prop_t LV_STYLE_CSS_IMG_SCALE;
extern lv_style_prop_t LV_STYLE_CSS_OVERFLOW;
extern lv_style_prop_t LV_STYLE_CSS_OVERFLOW_SCROLLING;
extern lv_style_prop_t LV_STYLE_CSS_POSITION;
extern lv_style_prop_t LV_STYLE_CSS_SCROLL_ENABLE_SNAP;
extern lv_style_prop_t LV_STYLE_CSS_SCROLL_SNAP_X;
extern lv_style_prop_t LV_STYLE_CSS_SCROLL_SNAP_Y;
extern lv_style_prop_t LV_STYLE_CSS_TEXT_OVERFLOW;

lv_style_prop_t lvjs_style_register_prop(void);
void lvgljs_style_css_prop_init(void);

#ifdef __cplusplus
}
#endif

#endif
