/* Auto-generated by scripts/lv_conf_gen.py - do not edit by hand. */

#include "lv_style_prop_extend.h"

lv_style_prop_t LV_STYLE_CSS_CHART_SCALE_X;
lv_style_prop_t LV_STYLE_CSS_CHART_SCALE_Y;
lv_style_prop_t LV_STYLE_CSS_DISPLAY;
lv_style_prop_t LV_STYLE_CSS_FLEX_ALIGN;
lv_style_prop_t LV_STYLE_CSS_GRID_ALIGN;
lv_style_prop_t LV_STYLE_CSS_GRID_CHILD;
lv_style_prop_t LV_STYLE_CSS_GRID_TEMPLATE;
lv_style_prop_t LV_STYLE_CSS_IMG_ORIGIN;
lv_style_prop_t LV_STYLE_CSS_IMG_ROTATE;
lv_style_prop_t LV_STYLE_CSS_IMG_SCALE_X;
lv_style_prop_t LV_STYLE_CSS_IMG_SCALE_Y;
lv_style_prop_t LV_STYLE_CSS_OVERFLOW;
lv_style_prop_t LV_STYLE_CSS_OVERFLOW_SCROLLING;
lv_style_prop_t LV_STYLE_CSS_POSITION;
lv_style_prop_t LV_STYLE_CSS_SCROLL_ENABLE_SNAP;
lv_style_prop_t LV_STYLE_CSS_SCROLL_SNAP_X;
lv_style_prop_t LV_STYLE_CSS_SCROLL_SNAP_Y;
lv_style_prop_t LV_STYLE_CSS_TEXT_OVERFLOW;

void lvgljs_style_css_prop_init(void)
{
    LV_STYLE_CSS_CHART_SCALE_X = lvjs_style_register_prop();
    LV_STYLE_CSS_CHART_SCALE_Y = lvjs_style_register_prop();
    LV_STYLE_CSS_DISPLAY = lvjs_style_register_prop();
    LV_STYLE_CSS_FLEX_ALIGN = lvjs_style_register_prop();
    LV_STYLE_CSS_GRID_ALIGN = lvjs_style_register_prop();
    LV_STYLE_CSS_GRID_CHILD = lvjs_style_register_prop();
    LV_STYLE_CSS_GRID_TEMPLATE = lvjs_style_register_prop();
    LV_STYLE_CSS_IMG_ORIGIN = lvjs_style_register_prop();
    LV_STYLE_CSS_IMG_ROTATE = lvjs_style_register_prop();
    LV_STYLE_CSS_IMG_SCALE_X = lvjs_style_register_prop();
    LV_STYLE_CSS_IMG_SCALE_Y = lvjs_style_register_prop();
    LV_STYLE_CSS_OVERFLOW = lvjs_style_register_prop();
    LV_STYLE_CSS_OVERFLOW_SCROLLING = lvjs_style_register_prop();
    LV_STYLE_CSS_POSITION = lvjs_style_register_prop();
    LV_STYLE_CSS_SCROLL_ENABLE_SNAP = lvjs_style_register_prop();
    LV_STYLE_CSS_SCROLL_SNAP_X = lvjs_style_register_prop();
    LV_STYLE_CSS_SCROLL_SNAP_Y = lvjs_style_register_prop();
    LV_STYLE_CSS_TEXT_OVERFLOW = lvjs_style_register_prop();
}
